**Code Vision OCR Submodel**

**Importing Dependencies**

In [ ]:
!pip install Levenshtein
import Levenshtein

Requirement already satisfied: Levenshtein in /usr/local/lib/python3.11/dist-packages (0.27.1)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.9.0 in /usr/local/lib/python3.11/dist-packages (from Levenshtein) (3.13.0)

In [ ]:
!pip install --upgrade google-cloud-vision
from google.cloud import vision

Requirement already satisfied: google-cloud-vision in /usr/local/lib/python3.11/dist-packages (3.10.1)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-vision) (2.24.2)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1 in /usr/local/lib/python3.11/dist-packages (from google-cloud-vision) (2.38.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-cloud-vision) (1.26.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2 in /usr/local/lib/python3.11/dist-packages (from google-cloud-vision) (5.29.4)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-vision) (1.70.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /usr/local/lib/python3.11/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-vision) (2.32.3)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-vision) (1.71.0)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-vision) (1.71.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-vision) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-vision) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-vision) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-vision) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-vision) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-vision) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-vision) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-vision) (2025.4.26)

In [ ]:
import io
import os
import pandas as pd
from PIL import Image, ImageEnhance
import re
import cv2
import numpy as np

In [ ]:
!unzip /content/screenshots-gen-ai.zip

Archive:  /content/screenshots-gen-ai.zip
   creating: screenshots-gen-ai/
  inflating: screenshots-gen-ai/.DS_Store
   creating: screenshots-gen-ai/python/
   creating: screenshots-gen-ai/java/
  inflating: screenshots-gen-ai/python/88.png
  inflating: screenshots-gen-ai/python/77.png
  inflating: screenshots-gen-ai/python/63.png
  inflating: screenshots-gen-ai/python/62.png
  inflating: screenshots-gen-ai/python/76.png
  inflating: screenshots-gen-ai/python/89.png
  inflating: screenshots-gen-ai/python/60.png
  inflating: screenshots-gen-ai/python/74.png
  inflating: screenshots-gen-ai/python/48.png
  inflating: screenshots-gen-ai/python/49.png
  inflating: screenshots-gen-ai/python/75.png
  inflating: screenshots-gen-ai/python/61.png
  inflating: screenshots-gen-ai/python/59.png
  inflating: screenshots-gen-ai/python/65.png
  inflating: screenshots-gen-ai/python/71.png
  inflating: screenshots-gen-ai/python/.DS_Store
  inflating: screenshots-gen-ai/python/70.png
  inflating: screenshots-gen-ai/python/64.png
  inflating: screenshots-gen-ai/python/58.png
  inflating: screenshots-gen-ai/python/99.png
  inflating: screenshots-gen-ai/python/8.png
  inflating: screenshots-gen-ai/python/72.png
  inflating: screenshots-gen-ai/python/66.png
  inflating: screenshots-gen-ai/python/67.png
  inflating: screenshots-gen-ai/python/73.png
  inflating: screenshots-gen-ai/python/9.png
  inflating: screenshots-gen-ai/python/98.png
  inflating: screenshots-gen-ai/python/14.png
  inflating: screenshots-gen-ai/python/28.png
  inflating: screenshots-gen-ai/python/29.png
  inflating: screenshots-gen-ai/python/15.png
  inflating: screenshots-gen-ai/python/17.png
  inflating: screenshots-gen-ai/python/16.png
  inflating: screenshots-gen-ai/python/12.png
  inflating: screenshots-gen-ai/python/13.png
  inflating: screenshots-gen-ai/python/39.png
  inflating: screenshots-gen-ai/python/11.png
  inflating: screenshots-gen-ai/python/10.png
  inflating: screenshots-gen-ai/python/38.png
  inflating: screenshots-gen-ai/python/35.png
  inflating: screenshots-gen-ai/python/21.png
  inflating: screenshots-gen-ai/python/20.png
  inflating: screenshots-gen-ai/python/34.png
  inflating: screenshots-gen-ai/python/22.png
  inflating: screenshots-gen-ai/python/36.png
  inflating: screenshots-gen-ai/python/37.png
  inflating: screenshots-gen-ai/python/23.png
  inflating: screenshots-gen-ai/python/27.png
  inflating: screenshots-gen-ai/python/33.png
  inflating: screenshots-gen-ai/python/32.png
  inflating: screenshots-gen-ai/python/26.png
  inflating: screenshots-gen-ai/python/18.png
  inflating: screenshots-gen-ai/python/30.png
  inflating: screenshots-gen-ai/python/24.png
  inflating: screenshots-gen-ai/python/25.png
  inflating: screenshots-gen-ai/python/31.png
  inflating: screenshots-gen-ai/python/19.png
  inflating: screenshots-gen-ai/python/95.png
  inflating: screenshots-gen-ai/python/81.png
  inflating: screenshots-gen-ai/python/4.png
  inflating: screenshots-gen-ai/python/56.png
  inflating: screenshots-gen-ai/python/42.png
  inflating: screenshots-gen-ai/python/43.png
  inflating: screenshots-gen-ai/python/5.png
  inflating: screenshots-gen-ai/python/57.png
  inflating: screenshots-gen-ai/python/80.png
  inflating: screenshots-gen-ai/python/94.png
  inflating: screenshots-gen-ai/python/82.png
  inflating: screenshots-gen-ai/python/96.png
  inflating: screenshots-gen-ai/python/41.png
  inflating: screenshots-gen-ai/python/55.png
  inflating: screenshots-gen-ai/python/7.png
  inflating: screenshots-gen-ai/python/69.png
  inflating: screenshots-gen-ai/python/68.png
  inflating: screenshots-gen-ai/python/54.png
  inflating: screenshots-gen-ai/python/6.png
  inflating: screenshots-gen-ai/python/40.png
  inflating: screenshots-gen-ai/python/97.png
  inflating: screenshots-gen-ai/python/83.png
  inflating: screenshots-gen-ai/python/87.png
  inflating: screenshots-gen-ai/python/93.png
  inflating: screenshots-gen-ai/python/78.png
  inflating: screenshots-gen-ai/python/44.png
  inflating: screenshots-gen-ai/python/2.png
  inflating: screenshots-gen-ai/python/50.png
  inflating: screenshots-gen-ai/python/3.png
  inflating: screenshots-gen-ai/python/51.png
  inflating: screenshots-gen-ai/python/45.png
  inflating: screenshots-gen-ai/python/79.png
  inflating: screenshots-gen-ai/python/92.png
  inflating: screenshots-gen-ai/python/86.png
  inflating: screenshots-gen-ai/python/90.png
  inflating: screenshots-gen-ai/python/84.png
  inflating: screenshots-gen-ai/python/53.png
  inflating: screenshots-gen-ai/python/1.png
  inflating: screenshots-gen-ai/python/47.png
  inflating: screenshots-gen-ai/python/46.png
  inflating: screenshots-gen-ai/python/52.png
  inflating: screenshots-gen-ai/python/0.png
  inflating: screenshots-gen-ai/python/85.png
  inflating: screenshots-gen-ai/python/91.png
  inflating: screenshots-gen-ai/java/88.png
  inflating: screenshots-gen-ai/java/77.png
  inflating: screenshots-gen-ai/java/63.png
  inflating: screenshots-gen-ai/java/62.png
  inflating: screenshots-gen-ai/java/76.png
  inflating: screenshots-gen-ai/java/89.png
  inflating: screenshots-gen-ai/java/60.png
  inflating: screenshots-gen-ai/java/74.png
  inflating: screenshots-gen-ai/java/48.png
  inflating: screenshots-gen-ai/java/49.png
  inflating: screenshots-gen-ai/java/75.png
  inflating: screenshots-gen-ai/java/61.png
  inflating: screenshots-gen-ai/java/59.png
  inflating: screenshots-gen-ai/java/65.png
  inflating: screenshots-gen-ai/java/71.png
  inflating: screenshots-gen-ai/java/.DS_Store
  inflating: screenshots-gen-ai/java/70.png
  inflating: screenshots-gen-ai/java/64.png
  inflating: screenshots-gen-ai/java/58.png
  inflating: screenshots-gen-ai/java/99.png
  inflating: screenshots-gen-ai/java/8.png
  inflating: screenshots-gen-ai/java/72.png
  inflating: screenshots-gen-ai/java/66.png
  inflating: screenshots-gen-ai/java/67.png
  inflating: screenshots-gen-ai/java/73.png
  inflating: screenshots-gen-ai/java/9.png
  inflating: screenshots-gen-ai/java/98.png
  inflating: screenshots-gen-ai/java/14.png
  inflating: screenshots-gen-ai/java/28.png
  inflating: screenshots-gen-ai/java/29.png
  inflating: screenshots-gen-ai/java/15.png
  inflating: screenshots-gen-ai/java/17.png
  inflating: screenshots-gen-ai/java/16.png
  inflating: screenshots-gen-ai/java/12.png
  inflating: screenshots-gen-ai/java/13.png
  inflating: screenshots-gen-ai/java/39.png
  inflating: screenshots-gen-ai/java/11.png
  inflating: screenshots-gen-ai/java/10.png
  inflating: screenshots-gen-ai/java/38.png
  inflating: screenshots-gen-ai/java/35.png
  inflating: screenshots-gen-ai/java/21.png
  inflating: screenshots-gen-ai/java/20.png
  inflating: screenshots-gen-ai/java/34.png
  inflating: screenshots-gen-ai/java/22.png
  inflating: screenshots-gen-ai/java/36.png
  inflating: screenshots-gen-ai/java/37.png
  inflating: screenshots-gen-ai/java/23.png
  inflating: screenshots-gen-ai/java/27.png
  inflating: screenshots-gen-ai/java/33.png
  inflating: screenshots-gen-ai/java/32.png
  inflating: screenshots-gen-ai/java/26.png
  inflating: screenshots-gen-ai/java/18.png
  inflating: screenshots-gen-ai/java/30.png
  inflating: screenshots-gen-ai/java/24.png
  inflating: screenshots-gen-ai/java/25.png
  inflating: screenshots-gen-ai/java/31.png
  inflating: screenshots-gen-ai/java/19.png
  inflating: screenshots-gen-ai/java/95.png
  inflating: screenshots-gen-ai/java/81.png
  inflating: screenshots-gen-ai/java/4.png
  inflating: screenshots-gen-ai/java/56.png
  inflating: screenshots-gen-ai/java/42.png
  inflating: screenshots-gen-ai/java/43.png
  inflating: screenshots-gen-ai/java/5.png
  inflating: screenshots-gen-ai/java/57.png
  inflating: screenshots-gen-ai/java/80.png
  inflating: screenshots-gen-ai/java/94.png
  inflating: screenshots-gen-ai/java/82.png
  inflating: screenshots-gen-ai/java/96.png
  inflating: screenshots-gen-ai/java/41.png
  inflating: screenshots-gen-ai/java/55.png
  inflating: screenshots-gen-ai/java/7.png
  inflating: screenshots-gen-ai/java/69.png
  inflating: screenshots-gen-ai/java/68.png
  inflating: screenshots-gen-ai/java/54.png
  inflating: screenshots-gen-ai/java/6.png
  inflating: screenshots-gen-ai/java/40.png
  inflating: screenshots-gen-ai/java/97.png
  inflating: screenshots-gen-ai/java/83.png
  inflating: screenshots-gen-ai/java/87.png
  inflating: screenshots-gen-ai/java/93.png
  inflating: screenshots-gen-ai/java/78.png
  inflating: screenshots-gen-ai/java/44.png
  inflating: screenshots-gen-ai/java/2.png
  inflating: screenshots-gen-ai/java/50.png
  inflating: screenshots-gen-ai/java/3.png
  inflating: screenshots-gen-ai/java/51.png
  inflating: screenshots-gen-ai/java/45.png
  inflating: screenshots-gen-ai/java/79.png
  inflating: screenshots-gen-ai/java/92.png
  inflating: screenshots-gen-ai/java/86.png
  inflating: screenshots-gen-ai/java/90.png
  inflating: screenshots-gen-ai/java/84.png
  inflating: screenshots-gen-ai/java/53.png
  inflating: screenshots-gen-ai/java/1.png
  inflating: screenshots-gen-ai/java/47.png
  inflating: screenshots-gen-ai/java/46.png
  inflating: screenshots-gen-ai/java/52.png
  inflating: screenshots-gen-ai/java/0.png
  inflating: screenshots-gen-ai/java/85.png
  inflating: screenshots-gen-ai/java/91.png

In [ ]:
!unzip /content/gen-ai-test.zip
!unzip /content/gen-ai-test-cs.zip

Archive:  /content/gen-ai-test.zip
   creating: gen-ai-test/
  inflating: gen-ai-test/.DS_Store
  inflating: __MACOSX/gen-ai-test/._.DS_Store
  inflating: gen-ai-test/8.png
  inflating: __MACOSX/gen-ai-test/._8.png
  inflating: gen-ai-test/9.png
  inflating: __MACOSX/gen-ai-test/._9.png
  inflating: gen-ai-test/14.png
  inflating: __MACOSX/gen-ai-test/._14.png
  inflating: gen-ai-test/15.png
  inflating: __MACOSX/gen-ai-test/._15.png
  inflating: gen-ai-test/17.png
  inflating: __MACOSX/gen-ai-test/._17.png
  inflating: gen-ai-test/16.png
  inflating: __MACOSX/gen-ai-test/._16.png
  inflating: gen-ai-test/12.png
  inflating: __MACOSX/gen-ai-test/._12.png
  inflating: gen-ai-test/13.png
  inflating: __MACOSX/gen-ai-test/._13.png
  inflating: gen-ai-test/11.png
  inflating: __MACOSX/gen-ai-test/._11.png
  inflating: gen-ai-test/10.png
  inflating: __MACOSX/gen-ai-test/._10.png
  inflating: gen-ai-test/18.png
  inflating: __MACOSX/gen-ai-test/._18.png
  inflating: gen-ai-test/19.png
  inflating: __MACOSX/gen-ai-test/._19.png
  inflating: gen-ai-test/4.png
  inflating: __MACOSX/gen-ai-test/._4.png
  inflating: gen-ai-test/5.png
  inflating: __MACOSX/gen-ai-test/._5.png
  inflating: gen-ai-test/7.png
  inflating: __MACOSX/gen-ai-test/._7.png
  inflating: gen-ai-test/6.png
  inflating: __MACOSX/gen-ai-test/._6.png
  inflating: gen-ai-test/2.png
  inflating: __MACOSX/gen-ai-test/._2.png
  inflating: gen-ai-test/3.png
  inflating: __MACOSX/gen-ai-test/._3.png
  inflating: gen-ai-test/1.png
  inflating: __MACOSX/gen-ai-test/._1.png
  inflating: gen-ai-test/0.png
  inflating: __MACOSX/gen-ai-test/._0.png
Archive:  /content/gen-ai-test-cs.zip
   creating: gen-ai-test-cs/
  inflating: gen-ai-test-cs/.DS_Store
  inflating: __MACOSX/gen-ai-test-cs/._.DS_Store
  inflating: gen-ai-test-cs/8.png
  inflating: __MACOSX/gen-ai-test-cs/._8.png
  inflating: gen-ai-test-cs/9.png
  inflating: __MACOSX/gen-ai-test-cs/._9.png
  inflating: gen-ai-test-cs/14.png
  inflating: __MACOSX/gen-ai-test-cs/._14.png
  inflating: gen-ai-test-cs/15.png
  inflating: __MACOSX/gen-ai-test-cs/._15.png
  inflating: gen-ai-test-cs/17.png
  inflating: __MACOSX/gen-ai-test-cs/._17.png
  inflating: gen-ai-test-cs/16.png
  inflating: __MACOSX/gen-ai-test-cs/._16.png
  inflating: gen-ai-test-cs/12.png
  inflating: __MACOSX/gen-ai-test-cs/._12.png
  inflating: gen-ai-test-cs/13.png
  inflating: __MACOSX/gen-ai-test-cs/._13.png
  inflating: gen-ai-test-cs/11.png
  inflating: __MACOSX/gen-ai-test-cs/._11.png
  inflating: gen-ai-test-cs/10.png
  inflating: __MACOSX/gen-ai-test-cs/._10.png
  inflating: gen-ai-test-cs/18.png
  inflating: __MACOSX/gen-ai-test-cs/._18.png
  inflating: gen-ai-test-cs/19.png
  inflating: __MACOSX/gen-ai-test-cs/._19.png
  inflating: gen-ai-test-cs/4.png
  inflating: __MACOSX/gen-ai-test-cs/._4.png
  inflating: gen-ai-test-cs/5.png
  inflating: __MACOSX/gen-ai-test-cs/._5.png
  inflating: gen-ai-test-cs/7.png
  inflating: __MACOSX/gen-ai-test-cs/._7.png
  inflating: gen-ai-test-cs/6.png
  inflating: __MACOSX/gen-ai-test-cs/._6.png
  inflating: gen-ai-test-cs/2.png
  inflating: __MACOSX/gen-ai-test-cs/._2.png
  inflating: gen-ai-test-cs/3.png
  inflating: __MACOSX/gen-ai-test-cs/._3.png
  inflating: gen-ai-test-cs/1.png
  inflating: __MACOSX/gen-ai-test-cs/._1.png
  inflating: gen-ai-test-cs/0.png
  inflating: __MACOSX/gen-ai-test-cs/._0.png

In [ ]:
def extract_code_from_image(image_path):
  os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = '/content/ocr-for-gen-ai-fac0fbc83a73.json'
  client = vision.ImageAnnotatorClient()

  with io.open(image_path,'rb') as image_file:
    content = image_file.read()

  image = vision.Image(content=content)
  response = client.document_text_detection(image=image)

  text = response.full_text_annotation.text
  return text

**Preprocessing Functions**

In [ ]:
def binarize_image(image_path):
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    binary = cv2.adaptiveThreshold(img, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                   cv2.THRESH_BINARY, 11, 2)
    #cv2.imwrite("binarized.png", binary)
    return "binarized.png"

def preprocess_image(input_path, output_path="processed.png"):
    img = Image.open(input_path).convert("L")  # grayscale
    enhancer = ImageEnhance.Contrast(img)
    enhanced_image = enhancer.enhance(2.0)
    enhanced_image.save(output_path)
    return output_path

**NLD**

In [ ]:
def normalized_levenshtein(s1, s2):

    dist = Levenshtein.distance(s1, s2)
    max_len = max(len(s1), len(s2))

    return dist / max_len if max_len > 0 else 0.0

def log_nld(index, nld, log_file="log.txt"):
    with open(log_file, "a") as f:
        f.write(f"Image {index} | NLD: {nld:.4f}\n")

def normalize(code):
    return ''.join(code.strip().split())

In [ ]:
def run(language,clean):
    df = pd.read_csv('ocr_data.csv') # ground truth code from csv dataset

    image_folder = f"/content/screenshots-gen-ai/{language}"

    nld_iter = []
    exact,accurate = 0,0

    for i in range(100):
        image_path = os.path.join(image_folder,f'{i}.png')
        #print(f"Using image {i}: {image_path}")

        if clean:
            cleaned_image = preprocess_image(image_path) # preprocessing
            #cleaned_image = binarize_image(image_path)
            code_text = extract_code_from_image(cleaned_image) #code extraction
        else:
            code_text = extract_code_from_image(image_path)
        cleaned_code = re.sub(r"\s+", "", code_text) #no whitespace

        #groundTruth code from csv
        if language == 'python':
            code_gt = df.iloc[i]['Code'] # for python
        elif language == 'java':
            code_gt = df.iloc[100+i]['Code'] # for java

        code_gt = code_gt.replace(r"\n", "\n")
        code_groundTruth = re.sub(r"\s+", "", code_gt) #no whitespace

        nld = normalized_levenshtein(normalize(cleaned_code),normalize(code_groundTruth))
        if nld >= 0.5:
            print(f"Image {i}.png → NLD: {nld:.4f}")
            print('code:',cleaned_code)
            print('groundTruth:',code_groundTruth)
        elif nld <= 0.05:
            exact += 1
            accurate += 1
        elif nld <= 0.1:
            accurate += 1
        nld_iter.append(nld)
        log_nld(i,nld=nld)

    avg = sum(nld_iter)/len(nld_iter)
    return nld_iter, avg, exact, accurate

In [ ]:
nld_iter, avg, exact, accurate = run('java',clean=True)
print(nld_iter)
print('Average NLD:', sum(nld_iter)/len(nld_iter))
print('Exact:', exact)
print('Accurate:', accurate)

[0.011627906976744186, 0.052941176470588235, 0.002145922746781116, 0.06167400881057269, 0.08670520231213873, 0.046232876712328765, 0.022091310751104567, 0.026455026455026454, 0.01411764705882353, 0.035830618892508145, 0.1308016877637131, 0.015625, 0.021108179419525065, 0.02557544757033248, 0.005952380952380952, 0.019490254872563718, 0.031067961165048542, 0.0390104662226451, 0.014644351464435146, 0.0035087719298245615, 0.06418918918918919, 0.005502063273727648, 0.020348837209302327, 0.006711409395973154, 0.02185792349726776, 0.0, 0.0, 0.017994858611825194, 0.007042253521126761, 0.006051437216338881, 0.010810810810810811, 0.010416666666666666, 0.05333333333333334, 0.09502762430939227, 0.018726591760299626, 0.06374501992031872, 0.019444444444444445, 0.056962025316455694, 0.016483516483516484, 0.0084985835694051, 0.027989821882951654, 0.012403100775193798, 0.007692307692307693, 0.014245014245014245, 0.00992063492063492, 0.02348993288590604, 0.041666666666666664, 0.046511627906976744, 0.05250596658711217, 0.03374578177727784, 0.0603448275862069, 0.030042918454935622, 0.014388489208633094, 0.007751937984496124, 0.023952095808383235, 0.01809954751131222, 0.016853932584269662, 0.008888888888888889, 0.008888888888888889, 0.01639344262295082, 0.019230769230769232, 0.028462998102466792, 0.012096774193548387, 0.10694183864915573, 0.02142857142857143, 0.031007751937984496, 0.026595744680851064, 0.021897810218978103, 0.022026431718061675, 0.10078740157480315, 0.020833333333333332, 0.016853932584269662, 0.0759493670886076, 0.023985239852398525, 0.1588447653429603, 0.039285714285714285, 0.044444444444444446, 0.06108597285067873, 0.034229828850855744, 0.028368794326241134, 0.12040133779264214, 0.09861325115562404, 0.018691588785046728, 0.07168458781362007, 0.028985507246376812, 0.029239766081871343, 0.024657534246575342, 0.02240325865580448, 0.015414258188824663, 0.02707275803722504, 0.18981481481481483, 0.02214022140221402, 0.03829787234042553, 0.011494252873563218, 0.00847457627118644, 0.007614213197969543, 0.06515580736543909, 0.02074688796680498, 0.051330798479087454, 0.003436426116838488]
Average NLD: 0.03415555815482134
Exact: 78
Accurate: 94

In [ ]:
def run_specific(language,clean):
    df = pd.read_csv('ocr_data.csv') # ground truth code from csv dataset

    image_folder = f"/content/screenshots-gen-ai/{language}"

    nld_iter = []
    exact,accurate = 0,0

    i = np.random.randint(0,99)

    image_path = os.path.join(image_folder,f'{i}.png')
    #print(f"Using image {i}: {image_path}")

    if clean:
        cleaned_image = preprocess_image(image_path) # preprocessing
            #cleaned_image = binarize_image(image_path)
        code_text = extract_code_from_image(cleaned_image) #code extraction
    else:
        code_text = extract_code_from_image(image_path)
    cleaned_code = re.sub(r"\s+", "", code_text) #no whitespace

    return normalize(cleaned_code)

In [ ]:
print(run_specific('java',clean=True))

//tryeachpossiblestartindexfromhaystackpublicintstrStr(Stringhaystack,Stringneedle){for(intindex=0;index<=haystack.length()-needle.length();index++){inti=index;intj=0;while(j<needle.length()&&haystack.charAt(i)==needle.charAt(j)){i++;j++;}if(j==needle.length()){//foundreturnindex;}}return-1;}

In [ ]:
def runJavaTest(clean):

    image_folder = f"/content/gen-ai-test"

    javaCodeTestList = []
    exact,accurate = 0,0

    for i in range(20):
        image_path = os.path.join(image_folder,f'{i}.png')
        #print(f"Using image {i}: {image_path}")

        if clean:
            cleaned_image = preprocess_image(image_path) # preprocessing
            #cleaned_image = binarize_image(image_path)
            code_text = extract_code_from_image(cleaned_image) #code extraction
        else:
            code_text = extract_code_from_image(image_path)
        cleaned_code = re.sub(r"\s+", "", code_text) #no whitespace
        javaCodeTestList.append(normalize(cleaned_code))

    return javaCodeTestList

In [ ]:
javaCodeTestList = runJavaTest(clean=True)
print(javaCodeTestList)

['publicvoidserialize(LittleEndianOutputout){out.writeShort(field_1_vcenter);}', 'publicvoidaddAll(BlockList<T>src){}if(src.size==0)return;intsrcDirIdx=0;for(;srcDirIdx<src.tailDirIdx;srcDirIdx++)addAll(src.directory[srcDirIdx],0,BLOCK_SIZE);if(src.tailBlkIdx!=0)addAll(src.tailBlock,0,src.tailBlkIdx);', 'publicvoidwriteByte(byteb){if(upto==blockSize){}}if(currentBlock!=null){}addBlock(currentBlock);currentBlock=newbyte[blockSize];upto=0;currentBlock[upto++]=b;', 'publicObjectIdgetObjectId(){returnobjectId;}', 'publicDeleteDomainEntryResultdeleteDomainEntry(DeleteDomainEntryRequestrequest){request=beforeClientExecution(request);returnexecuteDeleteDomainEntry(request);}', 'publiclongramBytesUsed(){}return((termOffsets!=null)?termOffsets.ramBytesUsed():0)+((termsDictOffsets!=null)?termsDictOffsets.ramBytesUsed():0);', 'publicfinalStringgetFullMessage(){byte[]raw=buffer;intmsgB=RawParseUtils.tagMessage(raw,if(msgB<0){return"";0);returnRawParseUtils.decode(guessEncoding(),raw,msgB,raw.length);}}', 'publicPOIFSFileSystem(){}this(true);_header.setBATCount(1);_header.setBATArray(newint[]{1});BATBlockbb=BATBlock.createEmptyBATBlock(bigBlockSize,false);bb.setOurBlockIndex(1);_bat_blocks.add(bb);setNextBlock(0,POIFSConstants.END_OF_CHAIN);setNextBlock(1,POIFSConstants.FAT_SECTOR_BLOCK);_property_table.setStartBlock(0);', 'publicvoidinit(intaddress){slice=pool.buffers[address>>ByteBlockPool.BYTE_BLOCK_SHIFT];assertslice!=null;upto=address&ByteBlockPool.BYTE_BLOCK_MASK;offset=address;assertupto<slice.length;}', 'publicSubmoduleAddCommandsetPath(Stringpath){this.pathpath;returnthis;}', 'publicListIngestionsResultlistIngestions(ListIngestionsRequestrequest){request=beforeClientExecution(request);returnexecuteListIngestions(request);}', 'publicQueryParserTokenManager(CharStreamstream,intlexState){}this(stream);SwitchTo(lexState);', 'publicGetShardIteratorResultgetShardIterator(GetShardIteratorRequestrequest){request=beforeClientExecution(request);returnexecuteGetShardIterator(request);}', 'publicModifyStrategyRequest(){super("aegis","2016-11-11","ModifyStrategy","vipaegis");setMethod(MethodType.POST);}', 'publicbooleanready()throwsIOException{synchronized(lock){if(in==null){}thrownewIOException("InputStreamReaderisclosed");try{returnbytes.hasRemaining()||in.available()>0;}catch(IOExceptione){}returnfalse;}', 'publicEscherOptRecordgetOptRecord(){return_optRecord;}', 'publicsynchronizedintread(byte[]buffer,intoffset,intlength){if(buffer}==null){thrownewNullPointerException("buffer==null");Arrays.checkOffsetAndCount(buffer.length,offset,length);==if(lengthreturn0;}intcopylen0){=count-pos<length?countpos:length;-for(inti=}0;i<copylen;i++){buffer[offset+i]=(byte)this.buffer.charAt(pos+i);pos+=copylen;returncopylen;}', 'publicOpenNLPSentenceBreakIterator(NLPSentenceDetectorOpsentence0p){}this.sentenceOp=sentenceOp;', 'publicvoidprint(Stringstr){}write(str!=null?str:String.valueOf((Object)null));', 'publicNotImplementedFunctionException(StringfunctionName,NotImplementedExceptioncause){super(functionName,cause);this.functionName=}functionName;']

In [ ]:
def runCSTest(clean):

    image_folder = f"/content/gen-ai-test-cs"

    csCodeTestList = []
    exact,accurate = 0,0

    for i in range(20):
        image_path = os.path.join(image_folder,f'{i}.png')
        #print(f"Using image {i}: {image_path}")

        if clean:
            cleaned_image = preprocess_image(image_path) # preprocessing
            #cleaned_image = binarize_image(image_path)
            code_text = extract_code_from_image(cleaned_image) #code extraction
        else:
            code_text = extract_code_from_image(image_path)
        cleaned_code = re.sub(r"\s+", "", code_text) #no whitespace
        csCodeTestList.append(normalize(cleaned_code))

    return csCodeTestList

In [ ]:
csCodeTestList = runCSTest(clean=True)
print(csCodeTestList)

['publicoverridevoidSerialize(ILittleEndianOutputout1){out1.WriteShort(field_1_vcenter);}', 'publicvirtualvoidAddAll(NGit.Util.BlockList<T>src){if(src.size==0){return;}intsrcDirIdx=0;for(;srcDirIdx<src.tailDirIdx%;srcDirIdx++){}AddAll(src.directory[srcDirIdx],0,BLOCK_SIZE);if(src.tailBlkIdx!=0){}}AddAll(src.tailBlock,0,src.tailBlkIdx);', '{publicoverridevoidWriteByte(byteb)if(outerInstance.upto==={outerInstance.blockSize)if(outerInstance.currentBlock!=null){outerInstance.blocks.Add(outerInstance.currentBlock);outerInstance.blockEnd.Add(outerInstance.upto);}}outerInstance.currentBlock=newbyte[outerInstance.blockSize];outerInstance.upto=0;}outerInstance.currentBlock[outerInstance.upto++]=b;', 'publicvirtualObjectIdGetObjectId(){returnobjectId;}', 'publicvirtualDeleteDomainEntryResponseDeleteDomainEntry(DeleteDomainEntryRequestrequest){varoptions=newInvokeOptions{};RequestMarshaller=DeleteDomainEntryRequestMarshaller.Instance,ResponseUnmarshaller=DeleteDomainEntryResponseUnmarshaller.Instance}returnInvoke<DeleteDomainEntryResponse>(request,options);', 'publicvirtuallongRamBytesUsed(){}returnfst==null?0:fst.GetSizeInBytes();', 'publicstringGetFullMessage()byte[]raw=buffer;{intmsgB=RawParseUtils.TagMessage(raw,0);if(msgB<0){returnstring.Empty;}}Encodingenc=RawParseUtils.ParseEncoding(raw);returnRawParseUtils.Decode(enc,raw,msgB,raw.Length);', 'publicPOIFSFileSystem(){HeaderBlockheaderBlock=newHeaderBlock(bigBlockSize);_property_table=newPropertyTable(headerBlock);_documents=newArrayList();_root=null;}', 'publicvoidInit(intaddress){slice=pool.Buffers[address>>ByteBlockPool.BYTE_BLOCK_SHIFT];Debug.Assert(slice!=null);upto=address&ByteBlockPool.BYTE_BLOCK_MASK;offset=address;Debug.Assert(upto<slice.Length);}', 'publicvirtualNGit.Api.SubmoduleAddCommandSetPath(stringpath){this.path=path;returnthis;}', 'publicvirtualListIngestionsResponseListIngestions(ListIngestionsRequestrequest){}varoptions=newInvokeOptions{};RequestMarshaller=ListIngestionsRequestMarshaller.Instance,ResponseUnmarshaller=ListIngestionsResponseUnmarshaller.InstancereturnInvoke<ListIngestionsResponse>(request,options);', 'publicQueryParserTokenManager(ICharStreamstream,intlexState){:this(stream)SwitchTo(lexState);}', 'publicvirtualGetShardIteratorResponseGetShardIterator(GetShardIteratorRequestrequest){varoptions=newInvoke0ptions{};RequestMarshaller=GetShardIteratorRequestMarshaller.Instance,ResponseUnmarshaller=GetShardIteratorResponseUnmarshaller.Instance}returnInvoke<GetShardIteratorResponse>(request,options);', 'publicModifyStrategyRequest():base("aegis","2016-11-11","ModifyStrategy","vipaegis","openAPI"){Method=MethodType.POST;}', 'publicoverrideboolReady(){lock(@lock){if(@in==null){}thrownewIOException("InputStreamReaderisclosed");}}try{}returnbytes.HasRemaining()||@in.Available()>0;catch(IOException){returnfalse;}', 'protectedinternalEscherOptRecordGetOptRecord(){return_optRecord;}', 'publicoverrideintRead(byte[]buffer,intoffset,intlength)lock(this){{if(buffer==null){thrownewArgumentNullException(nameof(buffer));}java.util.Arrays.checkOffsetAndCount(buffer.Length,offset,length);0)if(length=={return0;}intavailable=count-pos;intcopylen=available<length?available:length;for(inti=0;i<copylen;i++){buffer[offset+i]=unchecked((byte)this.buffer[pos+i]);}pos+=copylen;returncopylen;}}', 'publicOpenNLPSentenceBreakIterator(NLPSentenceDetectorOpsentence0p){this.sentenceOp=sentence0p;}', '{publicvirtualvoidPrint(stringstr)}write(str??Sharpen.StringHelper.GetValueOf((object)null));', 'publicNotImplementedFunctionException(stringfunctionName,NotImplementedExceptioncause):base(functionName,cause){this.functionName=functionName;}']

**Code Translation Submodel**

**Installing Library Dependencies**

In [ ]:
!pip install datasets
!pip install evaluate

Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (3.5.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.15)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.30.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.20.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: evaluate in /usr/local/lib/python3.11/dist-packages (0.4.3)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.5.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.30.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate) (24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.18.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.11.15)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.20.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)

**Importing Dataset**

In [ ]:
from datasets import load_dataset

dataset = load_dataset("google/code_x_glue_cc_code_to_code_trans")
print(dataset.column_names)
print(dataset['train'][0])

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/6.52k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

validation-00000-of-00001.parquet:   0%|          | 0.00/90.8k [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/170k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/10300 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/500 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

{'train': ['id', 'java', 'cs'], 'validation': ['id', 'java', 'cs'], 'test': ['id', 'java', 'cs']}
{'id': 0, 'java': 'public ListSpeechSynthesisTasksResult listSpeechSynthesisTasks(ListSpeechSynthesisTasksRequest request) {request = beforeClientExecution(request);return executeListSpeechSynthesisTasks(request);}\n', 'cs': 'public virtual ListSpeechSynthesisTasksResponse ListSpeechSynthesisTasks(ListSpeechSynthesisTasksRequest request){var options = new InvokeOptions();options.RequestMarshaller = ListSpeechSynthesisTasksRequestMarshaller.Instance;options.ResponseUnmarshaller = ListSpeechSynthesisTasksResponseUnmarshaller.Instance;return Invoke<ListSpeechSynthesisTasksResponse>(request, options);}\n'}

**Baseline Testing & Evaluation** \\
We will be testing two baseline models: CodeT5-Small and CodeT5-Base. For each model, we will be evaluating the model's performance on Java to C# translations and also C# to Java. The functions below define the model loading and evaluation process using the *code_x_glue* test dataset.

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch

def model_loader(model):
  if model=='base':
    model_name = "Salesforce/codet5-base"
  elif model=='small':
    model_name = "Salesforce/codet5-small"
  tokenizer = AutoTokenizer.from_pretrained(model_name)
  model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
  device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
  model.to(device)
  return tokenizer, model, device

In [ ]:
import evaluate
def javaToCSharp(tokenizer, model, device):
  predictions = []
  references = []

  print("Generating Java to C# translations ...")
  for example in dataset['test']:
      source_code = example["java"]
      reference_code = example["cs"]

      prompt = f"Translate Java to C#: {source_code}"

      inputs = tokenizer(prompt, return_tensors="pt", padding="max_length",
                        truncation=True, max_length=512)
      inputs = {k: v.to(device) for k, v in inputs.items()}

      outputs = model.generate(**inputs, max_length=512)
      translated_code = tokenizer.decode(outputs[0], skip_special_tokens=True)

      predictions.append(translated_code)
      references.append(reference_code)

  bleu_metric = evaluate.load("bleu")

  results = bleu_metric.compute(predictions=predictions, references=references)
  print("BLEU Score:", results["bleu"])

  exact_matches = 0
  for pred, ref in zip(predictions, references):
      if pred.strip() == ref.strip():
          exact_matches += 1

  exact_match_score = exact_matches / len(predictions)
  print("Exact Match Score:", exact_match_score)

def cSharpToJava(tokenizer, model, device):
  predictions = []
  references = []

  print("Generating C# to Java translations ...")
  for example in dataset['test']:
      source_code = example["cs"]
      reference_code = example["java"]

      prompt = f"Translate C# to Java: {source_code}"

      inputs = tokenizer(prompt, return_tensors="pt", padding="max_length",
                        truncation=True, max_length=512)
      inputs = {k: v.to(device) for k, v in inputs.items()}

      outputs = model.generate(**inputs, max_length=512)
      translated_code = tokenizer.decode(outputs[0], skip_special_tokens=True)

      predictions.append(translated_code)
      references.append(reference_code)

  bleu_metric = evaluate.load("bleu")

  results = bleu_metric.compute(predictions=predictions, references=references)
  print("BLEU Score:", results["bleu"])

  exact_matches = 0
  for pred, ref in zip(predictions, references):
      if pred.strip() == ref.strip():
          exact_matches += 1

  exact_match_score = exact_matches / len(predictions)
  print("Exact Match Score:", exact_match_score)

(i) CodeT5-Base Java → C#

In [ ]:
tokenizer, model, device = model_loader('base')
javaToCSharp(tokenizer, model, device)
cSharpToJava(tokenizer, model, device)

Generating Java to C# translations ...

Downloading builder script:   0%|          | 0.00/5.94k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/3.34k [00:00<?, ?B/s]

BLEU Score: 0.01606113600244783
Exact Match Score: 0.0
Generating C# to Java translations ...
BLEU Score: 0.03833964312526373
Exact Match Score: 0.0

(iii) CodeT5-Small Java → C# + C# → Java

In [ ]:
# 4 min 38s run time on T4
tokenizer, model, device = model_loader('small')
javaToCSharp(tokenizer, model, device)
cSharpToJava(tokenizer, model, device)

pytorch_model.bin:  95%|#########5| 231M/242M [00:00<?, ?B/s]

Generating Java to C# translations ...

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

BLEU Score: 0.0006631554077165196
Exact Match Score: 0.0
Generating C# to Java translations ...
BLEU Score: 0.0003011713015150887
Exact Match Score: 0.0

**Fine Tuning Methods** \\
As seen above, both CodeT5 models perform poorly without any fine-tuning as the original model was built around several tasks across multiple language (ie. code generation, translation, etc.). In order to be effective for our objective, we explore the following fine-tuning methods: Top-K Layer Fine-Tune and Low Rank Adaptation (LoRA).

Top-K Layer Fine-Tune

In [ ]:
model_name = "Salesforce/codet5-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# layer freeze
for param in model.parameters():
    param.requires_grad = False

K = 8  # adjust for number of layers

# layer unfreeze
for layer in model.encoder.block[-K:]:
    for param in layer.parameters():
        param.requires_grad = True
for layer in model.decoder.block[-K:]:
    for param in layer.parameters():
        param.requires_grad = True
for param in model.shared.parameters():
    param.requires_grad = True
for param in model.lm_head.parameters():
    param.requires_grad = True

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

tokenizer_config.json:   0%|          | 0.00/1.48k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/703k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/294k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/12.5k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.57k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/892M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

T5ForConditionalGeneration(
  (shared): Embedding(32100, 768)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32100, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32100, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=768, out_features=3072, bias=False)
              (wo): Linear(in_features=3072, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=768, out_features=32100, bias=False)
)

In [ ]:
def preprocess(example):
    # for Java to C#
    #inputs = ["translate java to CSharp: " + src for src in example["java"]]
    #targets = example["cs"]

    # for C# to Java
    inputs = ["translate CSharp to java: " + src for src in example["cs"]]
    targets = example["java"]

    model_inputs = tokenizer(
        inputs,
        truncation=True,
        padding="max_length",
        max_length=256
    )

    labels = tokenizer(
        targets,
        truncation=True,
        padding="max_length",
        max_length=256
    ).input_ids

    model_inputs["labels"] = labels
    return model_inputs

In [ ]:
tokenized_dataset = dataset.map(preprocess, batched=True)

Map:   0%|          | 0/10300 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [ ]:
### Top K training
from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments, DataCollatorForSeq2Seq

training_args = Seq2SeqTrainingArguments(
    output_dir=f"./codet5-topk-ft{K}",
    run_name=f"./codet5-topk-ft",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=5e-4, #original 5e-5
    num_train_epochs=3,
    logging_dir="./logs",
    fp16=True,
    save_steps=500,
    logging_steps=100,
    eval_steps=500,
    save_total_limit=2
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    tokenizer=tokenizer,
    data_collator=DataCollatorForSeq2Seq(tokenizer, model=model),
)

trainer.train()
trainer.evaluate()

<ipython-input-19-81267605b1af>:19: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: lhsu2 (lhsu2-carnegie-mellon-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

{'eval_loss': 0.04027503728866577,
 'eval_runtime': 8.1414,
 'eval_samples_per_second': 61.414,
 'eval_steps_per_second': 7.738,
 'epoch': 3.0}

In [ ]:
def translate_example(example):
    # Java to CSharp
    #source_code = example['java']
    #input_text = "translate java to CSharp: " + source_code

    # CSharp to Java
    source_code = example['cs']
    input_text = "translate CSharp to java: " + source_code

    inputs = tokenizer(
        input_text,
        return_tensors="pt",
        padding="max_length",
        truncation=True,
        max_length=512
    )

    inputs = {k: v.to(device) for k, v in inputs.items()}
    outputs = model.generate(**inputs, max_length=512)
    translated_code = tokenizer.decode(outputs[0], skip_special_tokens=True)

    example['predicted'] = translated_code
    return example

In [ ]:
def translate_specific_code(codeString):
    # Java to CSharp
    #input_text = "translate java to CSharp: " + codeString

    # CSharp to Java
    input_text = "translate CSharp to java: " + codeString

    inputs = tokenizer(
        input_text,
        return_tensors="pt",
        padding="max_length",
        truncation=True,
        max_length=512
    )

    inputs = {k: v.to(device) for k, v in inputs.items()}
    outputs = model.generate(**inputs, max_length=512)
    translated_code = tokenizer.decode(outputs[0], skip_special_tokens=True)

    return translated_code

In [ ]:
#java code from ocr
java_code = run_specific('java',clean=True)
print(java_code)
translation = translate_specific_code(java_code)
print(translation)

publicintjump(int()nums){intn=nums.length;int[]dp=newint[n];for(inti=1;i<n;i++){intsteps=Integer.MAX_VALUE;for(intj=i−1;j>=0;j--){if(dp[j]!=Integer.MAX_VALUE&&nums[j]+j>=i){steps=Math.min(steps,dp[j]+1);}=dp[i]steps;}}}returndp[n-1];
public int Jump(int[] dp){intn = ((int)nums.Length);int[] dp = newint[n];for (inti = 1; i < n; i++){intsteps = int.MaxValue;for (intj = i− 1; j >= 0; j--){if (dp[j] != int.MaxValue&&nums[j + j >= i){steps = Math.Min(steps,dp[j + 1]);}=dp[i]steps;}}}return dp[n - 1];}

**Java → C# Full Pipeline Test**

In [ ]:
def translationJavaTest(codeList):
  translationList = []
  for i in range(len(codeList)):
      sourceCodeString = codeList[i]
      translation = translate_specific_code(sourceCodeString)
      translationList.append(translation)
  return translationList

In [ ]:
javaCodeTestList = runJavaTest(clean=True)
refs = translationJavaTest(javaCodeTestList)
preds = pd.read_csv('javaFinalTest.csv')
preds = preds.iloc[:,0].tolist()
print(preds,refs)
exact_matches = sum(p.strip() == r.strip() for p, r in zip(preds, refs))
em_score = exact_matches / len(preds) * 100

print(f"Exact Match: {em_score:.2f}%")

bleu = evaluate.load("bleu")
wrapped_refs = [[ref] for ref in refs]
bleu_score = bleu.compute(predictions=preds, references=wrapped_refs)
print("BLEU:", bleu_score["bleu"])

['public override void Serialize(ILittleEndianOutput out1){out1.WriteShort(field_1_vcenter);}', 'public virtual void AddAll(NGit.Util.BlockList<T> src){if (src.size == 0){return;}int srcDirIdx = 0;for (; srcDirIdx < src.tailDirIdx; srcDirIdx++){AddAll(src.directory[srcDirIdx], 0, BLOCK_SIZE);}if (src.tailBlkIdx != 0){AddAll(src.tailBlock, 0, src.tailBlkIdx);}}', 'public override void WriteByte(byte b){if (outerInstance.upto == outerInstance.blockSize){if (outerInstance.currentBlock != null){outerInstance.blocks.Add(outerInstance.currentBlock);outerInstance.blockEnd.Add(outerInstance.upto);}outerInstance.currentBlock = new byte[outerInstance.blockSize];outerInstance.upto = 0;}outerInstance.currentBlock[outerInstance.upto++] = (byte)b;}', 'public virtual ObjectId GetObjectId(){return objectId;}', 'public virtual DeleteDomainEntryResponse DeleteDomainEntry(DeleteDomainEntryRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteDomainEntryRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteDomainEntryResponseUnmarshaller.Instance;return Invoke<DeleteDomainEntryResponse>(request, options);}', 'public virtual long RamBytesUsed(){return fst == null ? 0 : fst.GetSizeInBytes();}', 'public string GetFullMessage(){byte[] raw = buffer;int msgB = RawParseUtils.TagMessage(raw, 0);if (msgB < 0){return string.Empty;}Encoding enc = RawParseUtils.ParseEncoding(raw);return RawParseUtils.Decode(enc, raw, msgB, raw.Length);}', 'public POIFSFileSystem(){HeaderBlock headerBlock = new HeaderBlock(bigBlockSize);_property_table = new PropertyTable(headerBlock);_documents = new ArrayList();_root = null;}', 'public void Init(int address){slice = pool.Buffers[address >> ByteBlockPool.BYTE_BLOCK_SHIFT];Debug.Assert(slice != null);upto = address & ByteBlockPool.BYTE_BLOCK_MASK;offset0 = address;Debug.Assert(upto < slice.Length);}', 'public virtual NGit.Api.SubmoduleAddCommand SetPath(string path){this.path = path;return this;}', 'public virtual ListIngestionsResponse ListIngestions(ListIngestionsRequest request){var options = new InvokeOptions();options.RequestMarshaller = ListIngestionsRequestMarshaller.Instance;options.ResponseUnmarshaller = ListIngestionsResponseUnmarshaller.Instance;return Invoke<ListIngestionsResponse>(request, options);}', 'public QueryParserTokenManager(ICharStream stream, int lexState): this(stream){SwitchTo(lexState);}', 'public virtual GetShardIteratorResponse GetShardIterator(GetShardIteratorRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetShardIteratorRequestMarshaller.Instance;options.ResponseUnmarshaller = GetShardIteratorResponseUnmarshaller.Instance;return Invoke<GetShardIteratorResponse>(request, options);}', 'public ModifyStrategyRequest(): base("aegis", "2016-11-11", "ModifyStrategy", "vipaegis", "openAPI"){Method = MethodType.POST;}', 'public override bool ready(){lock (@lock){if (@in == null){throw new System.IO.IOException("InputStreamReader is closed");}try{return bytes.hasRemaining() || @in.available() > 0;}catch (System.IO.IOException){return false;}}}', 'protected internal EscherOptRecord GetOptRecord(){return _optRecord;}', 'public override int read(byte[] buffer, int offset, int length){lock (this){if (buffer == null){throw new System.ArgumentNullException("buffer == null");}java.util.Arrays.checkOffsetAndCount(buffer.Length, offset, length);if (length == 0){return 0;}int copylen = count - pos < length ? count - pos : length;{for (int i = 0; i < copylen; i++){buffer[offset + i] = unchecked((byte)this.buffer[pos + i]);}}pos += copylen;return copylen;}}', 'public OpenNLPSentenceBreakIterator(NLPSentenceDetectorOp sentenceOp){this.sentenceOp = sentenceOp;}', 'public virtual void print(string str){write(str != null ? str : Sharpen.StringHelper.GetValueOf((object)null));}', 'public NotImplementedFunctionException(string functionName, NotImplementedException cause): base(functionName,cause){this.functionName = functionName;}'] ['public override void Serialize(ILittleEndianOutput out1){out1.WriteShort(field_1_vcenter);}\n', 'public virtual void AddAll(BlockList<T> src){if (src.Count == 0){return;}intsrcDirIdx = 0;for (; srcDirIdx < src.tailDirIdx; srcDirIdx++){AddAll(src.directory[srcDirIdx], 0, BlockSize);}if (src.tailBlkIdx != 0){AddAll(src.tailBlock, 0, src.tailBlkIdx);}}if (src.tailBlkIdx != 0){AddAll(src.tailBlock, 0, src.tailBlkIdx);}}\n', 'public void WriteByte(byte b){if (upto == blockSize){break;}if (currentBlock != null){AddBlock(currentBlock);currentBlock = new byte[blockSize];upto = 0;currentBlock[upto++] = (byte)b;}\n', 'public virtual ObjectId GetObjectId(){return objectId;}\n', 'public virtual DeleteDomainEntryResponse DeleteDomainEntry(DeleteDomainEntryRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteDomainEntryRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteDomainEntryResponseUnmarshaller.Instance;return Invoke<DeleteDomainEntryResponse>(request, options);}\n', 'public longramBytesUsed(){return ((termOffsets != null) ? termOffsets.RamBytesUsed() : 0);}\n', 'public string GetFullMessage(){byte[] raw = buffer;intmsgB = RawParseUtils.TagMessage(raw, if (msgB < 0){return string.Empty;}return RawParseUtils.Decode(RawParseUtils.ParseEncoding(raw), msgB,raw.Length);}\n', 'publicPOIFSFileSystem(){this(true);_header.BATCount = 1;_header.BATArray = newint[]{1};BATBlockbb = BATBlock.CreateEmptyBATBlock(bigBlockSize, false);bb.OurBlockIndex = 1;_bat_blocks.Add(bb);SetNextBlock(0,POIFSConstants.END_OF_CHAIN);SetNextBlock(1,POIFSConstants.FAT_SECTOR_BLOCK);_property_table.StartBlock = (0);}\n', 'public void Init(intaddress){slice = pool.buffers[address >> ByteBlockPool.BYTE_BLOCK_SHIFT];Debug.Assert(slice != null);upto = address & ByteBlockPool.BYTE_BLOCK_MASK;offset = address;Debug.Assert(upto < slice.Length);}\n', 'public virtual NGit.Api.SubmoduleAddCommandsetPath(string path){this.pathpath = path;return this;}\n', 'public virtual ListIngestionsResponse ListIngestions(ListIngestionsRequest request){var options = new InvokeOptions();options.RequestMarshaller = ListIngestionsRequestMarshaller.Instance;options.ResponseUnmarshaller = ListIngestionsResponseUnmarshaller.Instance;return Invoke<ListIngestionsResponse>(request, options);}\n', 'public QueryParserTokenManager(ICharStreamstream stream, intlexState): this(stream){SwitchTo(lexState);}\n', 'public virtual GetShardIteratorResponse GetShardIterator(GetShardIteratorRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetShardIteratorRequestMarshaller.Instance;options.ResponseUnmarshaller = GetShardIteratorResponseUnmarshaller.Instance;return Invoke<GetShardIteratorResponse>(request, options);}\n', 'public ModifyStrategyRequest(): base("aegis",2016-11-11", "ModifyStrategy",vipaegis", "openAPI"){Method = MethodType.POST;}\n', 'public override bool ready(){lock (@lock){if (@in == null){throw new System.IO.IOException("InputStreamReaderisclosed");}try{returnbytes.hasRemaining() || @in.available() > 0;}catch (System.IO.IOException){return false;}}return true;}}\n', 'public EscherOptRecord GetOptRecord(){return _optRecord;}\n', 'public override int read(byte[] buffer, int offset, intlength){lock (this){if (buffer == null){throw newNullPointerException("buffer == null");}java.util.Arrays.checkOffsetAndCount(buffer.Length, offset, length);==if (lengthreturn0;}intcopylen0 = count - pos < length ? countpos : length;-for (inti = 0; i < copylen; i++){buffer[offset + i] = unchecked((byte)this.buffer[pos + i] = unchecked((byte)this.buffer[pos + i];pos += copylen;return copylen;}}\n', 'public OpenNLPSentenceBreakIterator(NLPSentenceDetectorOpsentence0p){this.sentenceOp = sentenceOp;}\n', 'public virtual void print(string str){write(str != null ? str : Sharpen.StringHelper.GetValueOf((object)null));}\n', 'publicNotImplementedFunctionException(string functionName,NotImplementedExceptioncause): base(functionName, cause){this.functionName = functionName;}\n']
Exact Match: 30.00%
BLEU: 0.7439294229660274

**C# → Java Full Pipeline Test**

In [ ]:
def translationCSTest(codeList):
  translationList = []
  for i in range(len(codeList)):
      sourceCodeString = codeList[i]
      translation = translate_specific_code(sourceCodeString)
      translationList.append(translation)
  return translationList

In [ ]:
csCodeTestList = runCSTest(clean=True)
refs = translationCSTest(csCodeTestList)
preds = pd.read_csv('csFinalTest.csv')
preds = preds.iloc[:,0].tolist()
print(preds,refs)
exact_matches = sum(p.strip() == r.strip() for p, r in zip(preds, refs))
em_score = exact_matches / len(preds) * 100

print(f"Exact Match: {em_score:.2f}%")

bleu = evaluate.load("bleu")
wrapped_refs = [[ref] for ref in refs]
bleu_score = bleu.compute(predictions=preds, references=wrapped_refs)
print("BLEU:", bleu_score["bleu"])

['public void serialize(LittleEndianOutput out) {out.writeShort(field_1_vcenter);}', 'public void addAll(BlockList<T> src) {if (src.size == 0)return;int srcDirIdx = 0;for (; srcDirIdx < src.tailDirIdx; srcDirIdx++)addAll(src.directory[srcDirIdx], 0, BLOCK_SIZE);if (src.tailBlkIdx != 0)addAll(src.tailBlock, 0, src.tailBlkIdx);}', 'public void writeByte(byte b) {if (upto == blockSize) {if (currentBlock != null) {addBlock(currentBlock);}currentBlock = new byte[blockSize];upto = 0;}currentBlock[upto++] = b;}', 'public ObjectId getObjectId() {return objectId;}', 'public DeleteDomainEntryResult deleteDomainEntry(DeleteDomainEntryRequest request) {request = beforeClientExecution(request);return executeDeleteDomainEntry(request);}', 'public long ramBytesUsed() {return ((termOffsets!=null)? termOffsets.ramBytesUsed() : 0) +((termsDictOffsets!=null)? termsDictOffsets.ramBytesUsed() : 0);}', 'public final String getFullMessage() {byte[] raw = buffer;int msgB = RawParseUtils.tagMessage(raw, 0);if (msgB < 0) {return ""; }return RawParseUtils.decode(guessEncoding(), raw, msgB, raw.length);}', 'public POIFSFileSystem() {this(true);_header.setBATCount(1);_header.setBATArray(new int[]{1});BATBlock bb = BATBlock.createEmptyBATBlock(bigBlockSize, false);bb.setOurBlockIndex(1);_bat_blocks.add(bb);setNextBlock(0, POIFSConstants.END_OF_CHAIN);setNextBlock(1, POIFSConstants.FAT_SECTOR_BLOCK);_property_table.setStartBlock(0);}', 'public void init(int address) {slice = pool.buffers[address >> ByteBlockPool.BYTE_BLOCK_SHIFT];assert slice != null;upto = address & ByteBlockPool.BYTE_BLOCK_MASK;offset0 = address;assert upto < slice.length;}', 'public SubmoduleAddCommand setPath(String path) {this.path = path;return this;}', 'public ListIngestionsResult listIngestions(ListIngestionsRequest request) {request = beforeClientExecution(request);return executeListIngestions(request);}', 'public QueryParserTokenManager(CharStream stream, int lexState){this(stream);SwitchTo(lexState);}', 'public GetShardIteratorResult getShardIterator(GetShardIteratorRequest request) {request = beforeClientExecution(request);return executeGetShardIterator(request);}', 'public ModifyStrategyRequest() {super("aegis", "2016-11-11", "ModifyStrategy", "vipaegis");setMethod(MethodType.POST);}', 'public boolean ready() throws IOException {synchronized (lock) {if (in == null) {throw new IOException("InputStreamReader is closed");}try {return bytes.hasRemaining() || in.available() > 0;} catch (IOException e) {return false;}}}', 'public EscherOptRecord getOptRecord() {return _optRecord;}', 'public synchronized int read(byte[] buffer, int offset, int length) {if (buffer == null) {throw new NullPointerException("buffer == null");}Arrays.checkOffsetAndCount(buffer.length, offset, length);if (length == 0) {return 0;}int copylen = count - pos < length ? count - pos : length;for (int i = 0; i < copylen; i++) {buffer[offset + i] = (byte) this.buffer.charAt(pos + i);}pos += copylen;return copylen;}', 'public OpenNLPSentenceBreakIterator(NLPSentenceDetectorOp sentenceOp) {this.sentenceOp = sentenceOp;}', 'public void print(String str) {write(str != null ? str : String.valueOf((Object) null));}', 'public NotImplementedFunctionException(String functionName, NotImplementedException cause) {super(functionName, cause);this.functionName = functionName;}'] ['public void serialize(LittleEndianOutputout out) {out.writeShort(field_1_vcenter);}\n', 'public void addAll(BlockList<T> src) {if (src.size == 0)return;int srcDirIdx = 0;for (;srcDirIdx < src.tailDirIdx % ;srcDirIdx++) {addAll(src.directory[srcDirIdx],0,BLOCK_SIZE);if (src.tailBlkIdx != 0) {addAll(src.tailBlock,0,src.tailBlkIdx);}addAll(src.tailBlock,0,src.tailBlkIdx);}\n', 'public void writeByte(byteb) {if (upto ==={blockSize} && currentBlock != null) {addBlock(currentBlock);blockEnd.add(upto);}currentBlock = new byte[blockSize];upto = 0;}\n', 'public ObjectId getObjectId() {return objectId;}\n', 'public DeleteDomainEntryResult deleteDomainEntry(DeleteDomainEntryRequest request) {request = beforeClientExecution(request);return executeDeleteDomainEntry(request);}\n', 'public VSDBytesUsed() {return fst == null ? 0 : fst.ramBytesUsed();}\n', 'public String getFullMessage() {byte[] raw = buffer;int msgB = RawParseUtils.tagMessage(raw,0);if (msgB < 0) {return "";}}\n', 'public POIFSFileSystem() {_header_block = newHeaderBlock(bigBlockSize);_property_table = newPropertyTable(headerBlock);_documents = new ArrayList<>();_root = null;}\n', 'public void init(intaddress) {slice = pool.buffers[address >> ByteBlockPool.BYTE_BLOCK_SHIFT];assert slice != null;upto = address & ByteBlockPool.BYTE_BLOCK_MASK;offset = address;assert upto < slice.length;}\n', 'public SubmoduleAddCommandSetPath(String path) {this.path = path;return this;}\n', 'public ListIngestionsResult listIngestions(ListIngestionsRequest request) {request = beforeClientExecution(request);return executeListIngestions(request);}\n', 'public QueryParserTokenManager(CharStreamstream lexState){this(stream);SwitchTo(lexState);}\n', 'public GetShardIteratorResult getShardIterator(GetShardIteratorRequest request) {request = beforeClientExecution(request);return executeGetShardIterator(request);}\n', 'public ModifyStrategyRequest() {super("aegis","2016-11-11","ModifyStrategy","vipaegis");setMethod(MethodType.POST);}\n', 'public boolean ready() throws IOException {synchronized (lock) {if (in == null) {throw new IOException("InputStreamReaderisclosed");}}try {returnbytes.hasRemaining() || in.available() > 0;} catch (IOException e) {return false;}}\n', 'public EscherOptRecord getOptRecord() {return _optRecord;}\n', 'public synchronized intRead(byte[] buffer, intoffset, intlength) throws IOException {if (buffer == null) {throw new NullPointerException(nameof(buffer));}Arrays.checkOffsetAndCount(buffer.length, offset,length);0)if (length == 0) {return 0;}intavailable = count-pos;intcopylen =available < length ? available : length;for (inti = 0; i < copylen; i++) {buffer[offset+i] = (byte) buffer[pos+i]);}pos += copylen;return copylen;}\n', 'public OpenNLPSentenceBreakIterator(NLPSentenceDetectorOpsentence0p) {this.sentenceOp = sentence0p;}\n', 'public void print(String str) {print(str);}\n', 'public NotImplementedFunctionException(StringfunctionName,NotImplementedExceptioncause) {super(functionName,cause);this.functionName = functionName;}\n']
Exact Match: 25.00%

Downloading builder script:   0%|          | 0.00/5.94k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/3.34k [00:00<?, ?B/s]

BLEU: 0.670903540897831

In [ ]:
def batch_translate_examples(examples):
    #Java to CSharp
    inputs = ["translate java to CSharp: " + src for src in examples["java"]]

    #CSharp to Java
    #inputs = ["translate CSharp to java: " + src for src in examples["cs"]]

    tokenized_inputs = tokenizer(
        inputs,
        return_tensors="pt",
        padding="max_length",
        truncation=True,
        max_length=512
    ).to(device)

    # predictions
    outputs = model.generate(
        **tokenized_inputs,
        max_length=512,
        num_beams=5,
    )

    # outputs to strings
    predictions = tokenizer.batch_decode(outputs, skip_special_tokens=True)
    return {"predicted": predictions}

In [ ]:
translated_test_dataset = dataset["test"].map(batch_translate_examples, batched=True, batch_size=8)

Parameter 'function'=<function batch_translate_examples at 0x79e9cf32b2e0> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
WARNING:datasets.fingerprint:Parameter 'function'=<function batch_translate_examples at 0x79e9cf32b2e0> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [ ]:
preds = translated_test_dataset["predicted"]
refs = translated_test_dataset["java"]

exact_matches = sum(p.strip() == r.strip() for p, r in zip(preds, refs))
em_score = exact_matches / len(preds) * 100

print(f"Exact Match: {em_score:.2f}%")

bleu = evaluate.load("bleu")
wrapped_refs = [[ref] for ref in refs]
bleu_score = bleu.compute(predictions=preds, references=wrapped_refs)
print("BLEU:", bleu_score["bleu"])

LoRA

In [ ]:
import math
import torch.nn as nn
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq
)
from transformers.models.t5.modeling_t5 import T5Attention

class LoRALinear(nn.Linear):
  def __init__(self, in_features, out_features, bias=True, device=None,
               dtype=None, lora_rank=8, lora_alpha=16, lora_dropout=0.1):
    super().__init__(in_features, out_features, bias=bias,
                         device=device, dtype=dtype)
    self.has_weights_merged = False
    if lora_rank > 0:
      self.lora_dropout = nn.Dropout(lora_dropout)
      self.lora_scaling = lora_alpha / lora_rank
      self.lora_A = nn.Parameter(torch.empty(lora_rank, in_features,
                                              device=device, dtype=dtype))
      self.lora_B = nn.Parameter(torch.empty(out_features, lora_rank,
                                              device=device, dtype=dtype))
      self.lora_A.requires_grad = True
      self.lora_B.requires_grad = True
      self.reset_parameters()

  def is_lora(self):
    return hasattr(self, "lora_A")

  def reset_parameters(self):
    nn.Linear.reset_parameters(self)
    if self.is_lora():
        nn.init.kaiming_uniform_(self.lora_A, a=math.sqrt(5))
        nn.init.zeros_(self.lora_B)

  def forward(self, input):
    output = super().forward(input)
    if self.is_lora() and not self.has_weights_merged:
      dropped = self.lora_dropout(input)
      A = dropped @ self.lora_A.T
      BA = A @ self.lora_B.T
      output += self.lora_scaling * BA
    return output


  def train(self, mode=True):
    super().train(mode)
    if not self.is_lora():
      return self
    if mode:
      if self.has_weights_merged:
        self.weight.data -= self.lora_scaling * (self.lora_B @ self.lora_A)
        self.has_weights_merged = False
    else:
      if not self.has_weights_merged:
        self.weight.data += self.lora_scaling * (self.lora_B @ self.lora_A)
        self.has_weights_merged = True
    return self


  def eval(self):
    super().eval()
    if self.is_lora() and not self.has_weights_merged:
      self.weight.data += self.lora_scaling * (self.lora_B @ self.lora_A)
      self.has_weights_merged = True
    return self

In [ ]:
def replace_with_lora(model, rank=8, alpha=16, target=("q","v")):
  for module in model.modules():
    if isinstance(module, T5Attention):
      for component in target:
        lin = getattr(module, component)
        lora_lin = LoRALinear(lin.in_features, lin.out_features, bias=False,
                              lora_rank=rank, lora_alpha=alpha,
                              lora_dropout=0.1)
        lora_lin.weight.data = lin.weight.data.clone()
        setattr(module, component, lora_lin)

def freeze_non_lora(model):
  for name, parameter in model.named_parameters():
    if "lora_A" in name or "lora_B" in name:
      parameter.requires_grad = True

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("Salesforce/codet5-base")

def encode(datapoint):
  # Java to CSharp
  #model_inputs = tokenizer(datapoint["java"],truncation=True, max_length=512)
  #labels = tokenizer(datapoint["cs"],truncation=True, max_length=512).input_ids

  # CSharp to Java
  model_inputs = tokenizer(datapoint["cs"],truncation=True, max_length=512)
  labels = tokenizer(datapoint["java"],truncation=True, max_length=512).input_ids
  model_inputs["labels"] = labels
  return model_inputs

train_ds = dataset['train'].map(encode, batched=True, remove_columns=dataset['train'].column_names)

tokenizer_config.json:   0%|          | 0.00/1.48k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/703k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/294k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/12.5k [00:00<?, ?B/s]

Map:   0%|          | 0/10300 [00:00<?, ? examples/s]

In [ ]:
model = AutoModelForSeq2SeqLM.from_pretrained("Salesforce/codet5-base")
replace_with_lora(model, rank=8, alpha=16)
freeze_non_lora(model)

collator = DataCollatorForSeq2Seq(tokenizer, model=model)
args = TrainingArguments(
    "codet5_lora",
    report_to="none",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=4e-4,
    num_train_epochs=3,
    fp16=torch.cuda.is_available(),
    logging_steps=100,
    save_steps=1000
)

Trainer(model=model,
        args=args,
        train_dataset= train_ds,
        data_collator=collator).train()

model.eval()

model.save_pretrained("codet5_lora_final")
tokenizer.save_pretrained("codet5_lora_final")

config.json:   0%|          | 0.00/1.57k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/892M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

('codet5_lora_final/tokenizer_config.json',
 'codet5_lora_final/special_tokens_map.json',
 'codet5_lora_final/vocab.json',
 'codet5_lora_final/merges.txt',
 'codet5_lora_final/added_tokens.json',
 'codet5_lora_final/tokenizer.json')

In [ ]:
import evaluate
def javaToCSharp_specificTranslation(tokenizer, model, device,codeString):

  print("Generating Java to C# translation ...")
  source_code = codeString
  prompt = f"Translate Java to C#: {source_code}"
  inputs = tokenizer(prompt, return_tensors="pt", padding="max_length",
                        truncation=True, max_length=512)
  inputs = {k: v.to(device) for k, v in inputs.items()}

  outputs = model.generate(**inputs, max_length=512)
  translated_code = tokenizer.decode(outputs[0], skip_special_tokens=True)

  return translated_code

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained("codet5_lora_final")
tokenizer = AutoTokenizer.from_pretrained("codet5_lora_final")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def translationJavaTest(codeList):
  translationList = []
  for i in range(len(codeList)):
      sourceCodeString = codeList[i]
      translation = javaToCSharp_specificTranslation(tokenizer, model, device, sourceCodeString)
      translationList.append(translation)
  return translationList

javaCodeTestList = runJavaTest(clean=True)
refs = translationJavaTest(javaCodeTestList)
preds = pd.read_csv('javaFinalTest.csv')
preds = preds.iloc[:,0].tolist()
print(preds,refs)
exact_matches = sum(p.strip() == r.strip() for p, r in zip(preds, refs))
em_score = exact_matches / len(preds) * 100

print(f"Exact Match: {em_score:.2f}%")

bleu = evaluate.load("bleu")
wrapped_refs = [[ref] for ref in refs]
bleu_score = bleu.compute(predictions=preds, references=wrapped_refs)
print("BLEU:", bleu_score["bleu"])

Some weights of the model checkpoint at codet5_lora_final were not used when initializing T5ForConditionalGeneration: ['decoder.block.0.layer.0.SelfAttention.q.lora_A', 'decoder.block.0.layer.0.SelfAttention.q.lora_B', 'decoder.block.0.layer.0.SelfAttention.v.lora_A', 'decoder.block.0.layer.0.SelfAttention.v.lora_B', 'decoder.block.0.layer.1.EncDecAttention.q.lora_A', 'decoder.block.0.layer.1.EncDecAttention.q.lora_B', 'decoder.block.0.layer.1.EncDecAttention.v.lora_A', 'decoder.block.0.layer.1.EncDecAttention.v.lora_B', 'decoder.block.1.layer.0.SelfAttention.q.lora_A', 'decoder.block.1.layer.0.SelfAttention.q.lora_B', 'decoder.block.1.layer.0.SelfAttention.v.lora_A', 'decoder.block.1.layer.0.SelfAttention.v.lora_B', 'decoder.block.1.layer.1.EncDecAttention.q.lora_A', 'decoder.block.1.layer.1.EncDecAttention.q.lora_B', 'decoder.block.1.layer.1.EncDecAttention.v.lora_A', 'decoder.block.1.layer.1.EncDecAttention.v.lora_B', 'decoder.block.10.layer.0.SelfAttention.q.lora_A', 'decoder.block.10.layer.0.SelfAttention.q.lora_B', 'decoder.block.10.layer.0.SelfAttention.v.lora_A', 'decoder.block.10.layer.0.SelfAttention.v.lora_B', 'decoder.block.10.layer.1.EncDecAttention.q.lora_A', 'decoder.block.10.layer.1.EncDecAttention.q.lora_B', 'decoder.block.10.layer.1.EncDecAttention.v.lora_A', 'decoder.block.10.layer.1.EncDecAttention.v.lora_B', 'decoder.block.11.layer.0.SelfAttention.q.lora_A', 'decoder.block.11.layer.0.SelfAttention.q.lora_B', 'decoder.block.11.layer.0.SelfAttention.v.lora_A', 'decoder.block.11.layer.0.SelfAttention.v.lora_B', 'decoder.block.11.layer.1.EncDecAttention.q.lora_A', 'decoder.block.11.layer.1.EncDecAttention.q.lora_B', 'decoder.block.11.layer.1.EncDecAttention.v.lora_A', 'decoder.block.11.layer.1.EncDecAttention.v.lora_B', 'decoder.block.2.layer.0.SelfAttention.q.lora_A', 'decoder.block.2.layer.0.SelfAttention.q.lora_B', 'decoder.block.2.layer.0.SelfAttention.v.lora_A', 'decoder.block.2.layer.0.SelfAttention.v.lora_B', 'decoder.block.2.layer.1.EncDecAttention.q.lora_A', 'decoder.block.2.layer.1.EncDecAttention.q.lora_B', 'decoder.block.2.layer.1.EncDecAttention.v.lora_A', 'decoder.block.2.layer.1.EncDecAttention.v.lora_B', 'decoder.block.3.layer.0.SelfAttention.q.lora_A', 'decoder.block.3.layer.0.SelfAttention.q.lora_B', 'decoder.block.3.layer.0.SelfAttention.v.lora_A', 'decoder.block.3.layer.0.SelfAttention.v.lora_B', 'decoder.block.3.layer.1.EncDecAttention.q.lora_A', 'decoder.block.3.layer.1.EncDecAttention.q.lora_B', 'decoder.block.3.layer.1.EncDecAttention.v.lora_A', 'decoder.block.3.layer.1.EncDecAttention.v.lora_B', 'decoder.block.4.layer.0.SelfAttention.q.lora_A', 'decoder.block.4.layer.0.SelfAttention.q.lora_B', 'decoder.block.4.layer.0.SelfAttention.v.lora_A', 'decoder.block.4.layer.0.SelfAttention.v.lora_B', 'decoder.block.4.layer.1.EncDecAttention.q.lora_A', 'decoder.block.4.layer.1.EncDecAttention.q.lora_B', 'decoder.block.4.layer.1.EncDecAttention.v.lora_A', 'decoder.block.4.layer.1.EncDecAttention.v.lora_B', 'decoder.block.5.layer.0.SelfAttention.q.lora_A', 'decoder.block.5.layer.0.SelfAttention.q.lora_B', 'decoder.block.5.layer.0.SelfAttention.v.lora_A', 'decoder.block.5.layer.0.SelfAttention.v.lora_B', 'decoder.block.5.layer.1.EncDecAttention.q.lora_A', 'decoder.block.5.layer.1.EncDecAttention.q.lora_B', 'decoder.block.5.layer.1.EncDecAttention.v.lora_A', 'decoder.block.5.layer.1.EncDecAttention.v.lora_B', 'decoder.block.6.layer.0.SelfAttention.q.lora_A', 'decoder.block.6.layer.0.SelfAttention.q.lora_B', 'decoder.block.6.layer.0.SelfAttention.v.lora_A', 'decoder.block.6.layer.0.SelfAttention.v.lora_B', 'decoder.block.6.layer.1.EncDecAttention.q.lora_A', 'decoder.block.6.layer.1.EncDecAttention.q.lora_B', 'decoder.block.6.layer.1.EncDecAttention.v.lora_A', 'decoder.block.6.layer.1.EncDecAttention.v.lora_B', 'decoder.block.7.layer.0.SelfAttention.q.lora_A', 'decoder.block.7.layer.0.SelfAttention.q.lora_B', 'decoder.block.7.layer.0.SelfAttention.v.lora_A', 'decoder.block.7.layer.0.SelfAttention.v.lora_B', 'decoder.block.7.layer.1.EncDecAttention.q.lora_A', 'decoder.block.7.layer.1.EncDecAttention.q.lora_B', 'decoder.block.7.layer.1.EncDecAttention.v.lora_A', 'decoder.block.7.layer.1.EncDecAttention.v.lora_B', 'decoder.block.8.layer.0.SelfAttention.q.lora_A', 'decoder.block.8.layer.0.SelfAttention.q.lora_B', 'decoder.block.8.layer.0.SelfAttention.v.lora_A', 'decoder.block.8.layer.0.SelfAttention.v.lora_B', 'decoder.block.8.layer.1.EncDecAttention.q.lora_A', 'decoder.block.8.layer.1.EncDecAttention.q.lora_B', 'decoder.block.8.layer.1.EncDecAttention.v.lora_A', 'decoder.block.8.layer.1.EncDecAttention.v.lora_B', 'decoder.block.9.layer.0.SelfAttention.q.lora_A', 'decoder.block.9.layer.0.SelfAttention.q.lora_B', 'decoder.block.9.layer.0.SelfAttention.v.lora_A', 'decoder.block.9.layer.0.SelfAttention.v.lora_B', 'decoder.block.9.layer.1.EncDecAttention.q.lora_A', 'decoder.block.9.layer.1.EncDecAttention.q.lora_B', 'decoder.block.9.layer.1.EncDecAttention.v.lora_A', 'decoder.block.9.layer.1.EncDecAttention.v.lora_B', 'encoder.block.0.layer.0.SelfAttention.q.lora_A', 'encoder.block.0.layer.0.SelfAttention.q.lora_B', 'encoder.block.0.layer.0.SelfAttention.v.lora_A', 'encoder.block.0.layer.0.SelfAttention.v.lora_B', 'encoder.block.1.layer.0.SelfAttention.q.lora_A', 'encoder.block.1.layer.0.SelfAttention.q.lora_B', 'encoder.block.1.layer.0.SelfAttention.v.lora_A', 'encoder.block.1.layer.0.SelfAttention.v.lora_B', 'encoder.block.10.layer.0.SelfAttention.q.lora_A', 'encoder.block.10.layer.0.SelfAttention.q.lora_B', 'encoder.block.10.layer.0.SelfAttention.v.lora_A', 'encoder.block.10.layer.0.SelfAttention.v.lora_B', 'encoder.block.11.layer.0.SelfAttention.q.lora_A', 'encoder.block.11.layer.0.SelfAttention.q.lora_B', 'encoder.block.11.layer.0.SelfAttention.v.lora_A', 'encoder.block.11.layer.0.SelfAttention.v.lora_B', 'encoder.block.2.layer.0.SelfAttention.q.lora_A', 'encoder.block.2.layer.0.SelfAttention.q.lora_B', 'encoder.block.2.layer.0.SelfAttention.v.lora_A', 'encoder.block.2.layer.0.SelfAttention.v.lora_B', 'encoder.block.3.layer.0.SelfAttention.q.lora_A', 'encoder.block.3.layer.0.SelfAttention.q.lora_B', 'encoder.block.3.layer.0.SelfAttention.v.lora_A', 'encoder.block.3.layer.0.SelfAttention.v.lora_B', 'encoder.block.4.layer.0.SelfAttention.q.lora_A', 'encoder.block.4.layer.0.SelfAttention.q.lora_B', 'encoder.block.4.layer.0.SelfAttention.v.lora_A', 'encoder.block.4.layer.0.SelfAttention.v.lora_B', 'encoder.block.5.layer.0.SelfAttention.q.lora_A', 'encoder.block.5.layer.0.SelfAttention.q.lora_B', 'encoder.block.5.layer.0.SelfAttention.v.lora_A', 'encoder.block.5.layer.0.SelfAttention.v.lora_B', 'encoder.block.6.layer.0.SelfAttention.q.lora_A', 'encoder.block.6.layer.0.SelfAttention.q.lora_B', 'encoder.block.6.layer.0.SelfAttention.v.lora_A', 'encoder.block.6.layer.0.SelfAttention.v.lora_B', 'encoder.block.7.layer.0.SelfAttention.q.lora_A', 'encoder.block.7.layer.0.SelfAttention.q.lora_B', 'encoder.block.7.layer.0.SelfAttention.v.lora_A', 'encoder.block.7.layer.0.SelfAttention.v.lora_B', 'encoder.block.8.layer.0.SelfAttention.q.lora_A', 'encoder.block.8.layer.0.SelfAttention.q.lora_B', 'encoder.block.8.layer.0.SelfAttention.v.lora_A', 'encoder.block.8.layer.0.SelfAttention.v.lora_B', 'encoder.block.9.layer.0.SelfAttention.q.lora_A', 'encoder.block.9.layer.0.SelfAttention.q.lora_B', 'encoder.block.9.layer.0.SelfAttention.v.lora_A', 'encoder.block.9.layer.0.SelfAttention.v.lora_B']
- This IS expected if you are initializing T5ForConditionalGeneration from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing T5ForConditionalGeneration from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
Generating Java to C# translation ...
['public override void Serialize(ILittleEndianOutput out1){out1.WriteShort(field_1_vcenter);}', 'public virtual void AddAll(NGit.Util.BlockList<T> src){if (src.size == 0){return;}int srcDirIdx = 0;for (; srcDirIdx < src.tailDirIdx; srcDirIdx++){AddAll(src.directory[srcDirIdx], 0, BLOCK_SIZE);}if (src.tailBlkIdx != 0){AddAll(src.tailBlock, 0, src.tailBlkIdx);}}', 'public override void WriteByte(byte b){if (outerInstance.upto == outerInstance.blockSize){if (outerInstance.currentBlock != null){outerInstance.blocks.Add(outerInstance.currentBlock);outerInstance.blockEnd.Add(outerInstance.upto);}outerInstance.currentBlock = new byte[outerInstance.blockSize];outerInstance.upto = 0;}outerInstance.currentBlock[outerInstance.upto++] = (byte)b;}', 'public virtual ObjectId GetObjectId(){return objectId;}', 'public virtual DeleteDomainEntryResponse DeleteDomainEntry(DeleteDomainEntryRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteDomainEntryRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteDomainEntryResponseUnmarshaller.Instance;return Invoke<DeleteDomainEntryResponse>(request, options);}', 'public virtual long RamBytesUsed(){return fst == null ? 0 : fst.GetSizeInBytes();}', 'public string GetFullMessage(){byte[] raw = buffer;int msgB = RawParseUtils.TagMessage(raw, 0);if (msgB < 0){return string.Empty;}Encoding enc = RawParseUtils.ParseEncoding(raw);return RawParseUtils.Decode(enc, raw, msgB, raw.Length);}', 'public POIFSFileSystem(){HeaderBlock headerBlock = new HeaderBlock(bigBlockSize);_property_table = new PropertyTable(headerBlock);_documents = new ArrayList();_root = null;}', 'public void Init(int address){slice = pool.Buffers[address >> ByteBlockPool.BYTE_BLOCK_SHIFT];Debug.Assert(slice != null);upto = address & ByteBlockPool.BYTE_BLOCK_MASK;offset0 = address;Debug.Assert(upto < slice.Length);}', 'public virtual NGit.Api.SubmoduleAddCommand SetPath(string path){this.path = path;return this;}', 'public virtual ListIngestionsResponse ListIngestions(ListIngestionsRequest request){var options = new InvokeOptions();options.RequestMarshaller = ListIngestionsRequestMarshaller.Instance;options.ResponseUnmarshaller = ListIngestionsResponseUnmarshaller.Instance;return Invoke<ListIngestionsResponse>(request, options);}', 'public QueryParserTokenManager(ICharStream stream, int lexState): this(stream){SwitchTo(lexState);}', 'public virtual GetShardIteratorResponse GetShardIterator(GetShardIteratorRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetShardIteratorRequestMarshaller.Instance;options.ResponseUnmarshaller = GetShardIteratorResponseUnmarshaller.Instance;return Invoke<GetShardIteratorResponse>(request, options);}', 'public ModifyStrategyRequest(): base("aegis", "2016-11-11", "ModifyStrategy", "vipaegis", "openAPI"){Method = MethodType.POST;}', 'public override bool ready(){lock (@lock){if (@in == null){throw new System.IO.IOException("InputStreamReader is closed");}try{return bytes.hasRemaining() || @in.available() > 0;}catch (System.IO.IOException){return false;}}}', 'protected internal EscherOptRecord GetOptRecord(){return _optRecord;}', 'public override int read(byte[] buffer, int offset, int length){lock (this){if (buffer == null){throw new System.ArgumentNullException("buffer == null");}java.util.Arrays.checkOffsetAndCount(buffer.Length, offset, length);if (length == 0){return 0;}int copylen = count - pos < length ? count - pos : length;{for (int i = 0; i < copylen; i++){buffer[offset + i] = unchecked((byte)this.buffer[pos + i]);}}pos += copylen;return copylen;}}', 'public OpenNLPSentenceBreakIterator(NLPSentenceDetectorOp sentenceOp){this.sentenceOp = sentenceOp;}', 'public virtual void print(string str){write(str != null ? str : Sharpen.StringHelper.GetValueOf((object)null));}', 'public NotImplementedFunctionException(string functionName, NotImplementedException cause): base(functionName,cause){this.functionName = functionName;}'] ['public override void Serialize(ILittleEndianOutput out1){out1.WriteShort(field_1_vcenter);}\n', 'public void AddAll(IBlockList<T> src){if (src.Count == 0){return;}intsrcDirIdx = 0;for (;srcDirIdx < src.tailDirIdx;srcDirIdx++){AddAll(src.directory[srcDirIdx], 0, BLOCK_SIZE);}if (src.tailBlkIdx != 0){AddAll(src.tailBlock, 0, src.tailBlkIdx);}}}\n', 'public void TranslateJava to C#: AddByte(byte b){if (upto == blockSize){break;}if (currentBlock != null){blocks.Add(currentBlock);}currentBlock = newbyte[blockSize];upto = 0;currentBlock[upto++] = b;}\n', 'public virtual ITranslate Java to C#: publicObjectIdGetObjectId(){return objectId;}\n', 'public virtual DeleteDomainEntryResponse DeleteDomainEntry(DeleteDomainEntryRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteDomainEntryRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteDomainEntryResponseUnmarshaller.Instance;return Invoke<DeleteDomainEntryResponse>(request, options);}\n', 'public override long RamBytesUsed(){return ((termOffsets != null) ? termOffsets.RamBytesUsed() : 0);}\n', 'public string GetFullMessage(){byte[] raw = buffer;int msgB = RawParseUtils.TagMessage(raw, if (msgB < 0){return string.Empty;}return RawParseUtils.Decode(Constants.ParseEncoding(),raw, msgB,raw.Length);}}\n', 'public POIFSFileSystem(): this(true){_header.BATCount = 1;_header.BATArray = newint[]{1});BATBlockbb = BATBlock.CreateEmptyBATBlock(bigBlockSize, false);bb.OurBlockIndex = 1;_bat_blocks.Add(bb);SetNextBlock(0, POIFSConstants.END_OF_CHAIN);SetNextBlock(1, POIFSConstants.FAT_SECTOR_BLOCK);_property_table.SetStartBlock(0);}\n', 'public void Init(int address){slice = pool.Buffers[address >> ByteBlockPool.BYTE_BLOCK_SHIFT];Debug.Assert(slice != null);upto = address & ByteBlockPool.BYTE_BLOCK_MASK;offset = address;Debug.Assert(upto < slice.Length);}\n', 'public virtual NGit.Api.SubmoduleAddCommand SetPath(string path){this.pathpath = path;return this;}\n', 'public virtual ListIngestionsResponse ListIngestions(ListIngestionsRequest request){var options = new InvokeOptions();options.RequestMarshaller = ListIngestionsRequestMarshaller.Instance;options.ResponseUnmarshaller = ListIngestionsResponseUnmarshaller.Instance;return Invoke<ListIngestionsResponse>(request, options);}\n', 'public QueryParserTokenManager(ICharStream stream, intlexState): this(stream){SwitchTo(lexState);}\n', 'public virtual GetShardIteratorResponse GetShardIterator(GetShardIteratorRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetShardIteratorRequestMarshaller.Instance;options.ResponseUnmarshaller = GetShardIteratorResponseUnmarshaller.Instance;return Invoke<GetShardIteratorResponse>(request, options);}\n', 'public ModifyStrategyRequest(): base("aegis",2016-11-11", ModifyStrategy",vipaegis", "openAPI"){Method = MethodType.POST;}\n', 'public override bool ready(){lock (@lock){if (@in == null){thrownew System.IO.IOException("InputStreamReaderisclosed");}try{return bytes.hasRemaining() || @in.available() > 0;}catch (System.IO.IOException){return false;}}return false;}}\n', 'public EscherOptRecord GetOptRecord(){return _optRecord;}\n', 'public virtual int read(byte[] buffer, int offset, int length){lock (this){if (buffer == null){thrownew System.ArgumentNullException("buffer == null");}java.util.Arrays.checkOffsetAndCount(buffer.Length, offset, length); == if (lengthreturn0){return count - pos < length ? countpos : length;}int copylen0 = count - pos < length ? countpos : length;-for (int i = 0; i < copylen; i++){buffer[offset + i] = unchecked((byte)this.buffer[pos + i]).CopyTo(copylen);pos += copylen;return copylen;}}\n', 'public Translate Java to C#: PublicOpenNLPSentenceBreakIterator(NLPSentenceDetectorOpsentence0p){this.sentenceOp = sentenceOp;}\n', 'public virtual void print(string str){write(str != null ? str : (object)null);}\n', 'public NotImplementedFunctionException(string functionName,NotImplementedException cause): base(functionName,cause){this.functionName = functionName;}\n']
Exact Match: 20.00%
BLEU: 0.7557675467807522

In [ ]:
import evaluate
def csToJava_specificTranslation(tokenizer, model, device,codeString):

  print("Generating C# to Java translation ...")
  source_code = codeString
  prompt = f"Translate C# to Java: {source_code}"
  inputs = tokenizer(prompt, return_tensors="pt", padding="max_length",
                        truncation=True, max_length=512)
  inputs = {k: v.to(device) for k, v in inputs.items()}

  outputs = model.generate(**inputs, max_length=512)
  translated_code = tokenizer.decode(outputs[0], skip_special_tokens=True)

  return translated_code

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained("codet5_lora_final")
tokenizer = AutoTokenizer.from_pretrained("codet5_lora_final")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

def translationCSTest(codeList):
  translationList = []
  for i in range(len(codeList)):
      sourceCodeString = codeList[i]
      translation = csToJava_specificTranslation(tokenizer, model, device, sourceCodeString)
      translationList.append(translation)
  return translationList

csCodeTestList = runCSTest(clean=True)
refs = translationCSTest(csCodeTestList)
preds = pd.read_csv('csFinalTest.csv')
preds = preds.iloc[:,0].tolist()
print(preds,refs)
exact_matches = sum(p.strip() == r.strip() for p, r in zip(preds, refs))
em_score = exact_matches / len(preds) * 100

print(f"Exact Match: {em_score:.2f}%")

bleu = evaluate.load("bleu")
wrapped_refs = [[ref] for ref in refs]
bleu_score = bleu.compute(predictions=preds, references=wrapped_refs)
print("BLEU:", bleu_score["bleu"])

Some weights of the model checkpoint at codet5_lora_final were not used when initializing T5ForConditionalGeneration: ['decoder.block.0.layer.0.SelfAttention.q.lora_A', 'decoder.block.0.layer.0.SelfAttention.q.lora_B', 'decoder.block.0.layer.0.SelfAttention.v.lora_A', 'decoder.block.0.layer.0.SelfAttention.v.lora_B', 'decoder.block.0.layer.1.EncDecAttention.q.lora_A', 'decoder.block.0.layer.1.EncDecAttention.q.lora_B', 'decoder.block.0.layer.1.EncDecAttention.v.lora_A', 'decoder.block.0.layer.1.EncDecAttention.v.lora_B', 'decoder.block.1.layer.0.SelfAttention.q.lora_A', 'decoder.block.1.layer.0.SelfAttention.q.lora_B', 'decoder.block.1.layer.0.SelfAttention.v.lora_A', 'decoder.block.1.layer.0.SelfAttention.v.lora_B', 'decoder.block.1.layer.1.EncDecAttention.q.lora_A', 'decoder.block.1.layer.1.EncDecAttention.q.lora_B', 'decoder.block.1.layer.1.EncDecAttention.v.lora_A', 'decoder.block.1.layer.1.EncDecAttention.v.lora_B', 'decoder.block.10.layer.0.SelfAttention.q.lora_A', 'decoder.block.10.layer.0.SelfAttention.q.lora_B', 'decoder.block.10.layer.0.SelfAttention.v.lora_A', 'decoder.block.10.layer.0.SelfAttention.v.lora_B', 'decoder.block.10.layer.1.EncDecAttention.q.lora_A', 'decoder.block.10.layer.1.EncDecAttention.q.lora_B', 'decoder.block.10.layer.1.EncDecAttention.v.lora_A', 'decoder.block.10.layer.1.EncDecAttention.v.lora_B', 'decoder.block.11.layer.0.SelfAttention.q.lora_A', 'decoder.block.11.layer.0.SelfAttention.q.lora_B', 'decoder.block.11.layer.0.SelfAttention.v.lora_A', 'decoder.block.11.layer.0.SelfAttention.v.lora_B', 'decoder.block.11.layer.1.EncDecAttention.q.lora_A', 'decoder.block.11.layer.1.EncDecAttention.q.lora_B', 'decoder.block.11.layer.1.EncDecAttention.v.lora_A', 'decoder.block.11.layer.1.EncDecAttention.v.lora_B', 'decoder.block.2.layer.0.SelfAttention.q.lora_A', 'decoder.block.2.layer.0.SelfAttention.q.lora_B', 'decoder.block.2.layer.0.SelfAttention.v.lora_A', 'decoder.block.2.layer.0.SelfAttention.v.lora_B', 'decoder.block.2.layer.1.EncDecAttention.q.lora_A', 'decoder.block.2.layer.1.EncDecAttention.q.lora_B', 'decoder.block.2.layer.1.EncDecAttention.v.lora_A', 'decoder.block.2.layer.1.EncDecAttention.v.lora_B', 'decoder.block.3.layer.0.SelfAttention.q.lora_A', 'decoder.block.3.layer.0.SelfAttention.q.lora_B', 'decoder.block.3.layer.0.SelfAttention.v.lora_A', 'decoder.block.3.layer.0.SelfAttention.v.lora_B', 'decoder.block.3.layer.1.EncDecAttention.q.lora_A', 'decoder.block.3.layer.1.EncDecAttention.q.lora_B', 'decoder.block.3.layer.1.EncDecAttention.v.lora_A', 'decoder.block.3.layer.1.EncDecAttention.v.lora_B', 'decoder.block.4.layer.0.SelfAttention.q.lora_A', 'decoder.block.4.layer.0.SelfAttention.q.lora_B', 'decoder.block.4.layer.0.SelfAttention.v.lora_A', 'decoder.block.4.layer.0.SelfAttention.v.lora_B', 'decoder.block.4.layer.1.EncDecAttention.q.lora_A', 'decoder.block.4.layer.1.EncDecAttention.q.lora_B', 'decoder.block.4.layer.1.EncDecAttention.v.lora_A', 'decoder.block.4.layer.1.EncDecAttention.v.lora_B', 'decoder.block.5.layer.0.SelfAttention.q.lora_A', 'decoder.block.5.layer.0.SelfAttention.q.lora_B', 'decoder.block.5.layer.0.SelfAttention.v.lora_A', 'decoder.block.5.layer.0.SelfAttention.v.lora_B', 'decoder.block.5.layer.1.EncDecAttention.q.lora_A', 'decoder.block.5.layer.1.EncDecAttention.q.lora_B', 'decoder.block.5.layer.1.EncDecAttention.v.lora_A', 'decoder.block.5.layer.1.EncDecAttention.v.lora_B', 'decoder.block.6.layer.0.SelfAttention.q.lora_A', 'decoder.block.6.layer.0.SelfAttention.q.lora_B', 'decoder.block.6.layer.0.SelfAttention.v.lora_A', 'decoder.block.6.layer.0.SelfAttention.v.lora_B', 'decoder.block.6.layer.1.EncDecAttention.q.lora_A', 'decoder.block.6.layer.1.EncDecAttention.q.lora_B', 'decoder.block.6.layer.1.EncDecAttention.v.lora_A', 'decoder.block.6.layer.1.EncDecAttention.v.lora_B', 'decoder.block.7.layer.0.SelfAttention.q.lora_A', 'decoder.block.7.layer.0.SelfAttention.q.lora_B', 'decoder.block.7.layer.0.SelfAttention.v.lora_A', 'decoder.block.7.layer.0.SelfAttention.v.lora_B', 'decoder.block.7.layer.1.EncDecAttention.q.lora_A', 'decoder.block.7.layer.1.EncDecAttention.q.lora_B', 'decoder.block.7.layer.1.EncDecAttention.v.lora_A', 'decoder.block.7.layer.1.EncDecAttention.v.lora_B', 'decoder.block.8.layer.0.SelfAttention.q.lora_A', 'decoder.block.8.layer.0.SelfAttention.q.lora_B', 'decoder.block.8.layer.0.SelfAttention.v.lora_A', 'decoder.block.8.layer.0.SelfAttention.v.lora_B', 'decoder.block.8.layer.1.EncDecAttention.q.lora_A', 'decoder.block.8.layer.1.EncDecAttention.q.lora_B', 'decoder.block.8.layer.1.EncDecAttention.v.lora_A', 'decoder.block.8.layer.1.EncDecAttention.v.lora_B', 'decoder.block.9.layer.0.SelfAttention.q.lora_A', 'decoder.block.9.layer.0.SelfAttention.q.lora_B', 'decoder.block.9.layer.0.SelfAttention.v.lora_A', 'decoder.block.9.layer.0.SelfAttention.v.lora_B', 'decoder.block.9.layer.1.EncDecAttention.q.lora_A', 'decoder.block.9.layer.1.EncDecAttention.q.lora_B', 'decoder.block.9.layer.1.EncDecAttention.v.lora_A', 'decoder.block.9.layer.1.EncDecAttention.v.lora_B', 'encoder.block.0.layer.0.SelfAttention.q.lora_A', 'encoder.block.0.layer.0.SelfAttention.q.lora_B', 'encoder.block.0.layer.0.SelfAttention.v.lora_A', 'encoder.block.0.layer.0.SelfAttention.v.lora_B', 'encoder.block.1.layer.0.SelfAttention.q.lora_A', 'encoder.block.1.layer.0.SelfAttention.q.lora_B', 'encoder.block.1.layer.0.SelfAttention.v.lora_A', 'encoder.block.1.layer.0.SelfAttention.v.lora_B', 'encoder.block.10.layer.0.SelfAttention.q.lora_A', 'encoder.block.10.layer.0.SelfAttention.q.lora_B', 'encoder.block.10.layer.0.SelfAttention.v.lora_A', 'encoder.block.10.layer.0.SelfAttention.v.lora_B', 'encoder.block.11.layer.0.SelfAttention.q.lora_A', 'encoder.block.11.layer.0.SelfAttention.q.lora_B', 'encoder.block.11.layer.0.SelfAttention.v.lora_A', 'encoder.block.11.layer.0.SelfAttention.v.lora_B', 'encoder.block.2.layer.0.SelfAttention.q.lora_A', 'encoder.block.2.layer.0.SelfAttention.q.lora_B', 'encoder.block.2.layer.0.SelfAttention.v.lora_A', 'encoder.block.2.layer.0.SelfAttention.v.lora_B', 'encoder.block.3.layer.0.SelfAttention.q.lora_A', 'encoder.block.3.layer.0.SelfAttention.q.lora_B', 'encoder.block.3.layer.0.SelfAttention.v.lora_A', 'encoder.block.3.layer.0.SelfAttention.v.lora_B', 'encoder.block.4.layer.0.SelfAttention.q.lora_A', 'encoder.block.4.layer.0.SelfAttention.q.lora_B', 'encoder.block.4.layer.0.SelfAttention.v.lora_A', 'encoder.block.4.layer.0.SelfAttention.v.lora_B', 'encoder.block.5.layer.0.SelfAttention.q.lora_A', 'encoder.block.5.layer.0.SelfAttention.q.lora_B', 'encoder.block.5.layer.0.SelfAttention.v.lora_A', 'encoder.block.5.layer.0.SelfAttention.v.lora_B', 'encoder.block.6.layer.0.SelfAttention.q.lora_A', 'encoder.block.6.layer.0.SelfAttention.q.lora_B', 'encoder.block.6.layer.0.SelfAttention.v.lora_A', 'encoder.block.6.layer.0.SelfAttention.v.lora_B', 'encoder.block.7.layer.0.SelfAttention.q.lora_A', 'encoder.block.7.layer.0.SelfAttention.q.lora_B', 'encoder.block.7.layer.0.SelfAttention.v.lora_A', 'encoder.block.7.layer.0.SelfAttention.v.lora_B', 'encoder.block.8.layer.0.SelfAttention.q.lora_A', 'encoder.block.8.layer.0.SelfAttention.q.lora_B', 'encoder.block.8.layer.0.SelfAttention.v.lora_A', 'encoder.block.8.layer.0.SelfAttention.v.lora_B', 'encoder.block.9.layer.0.SelfAttention.q.lora_A', 'encoder.block.9.layer.0.SelfAttention.q.lora_B', 'encoder.block.9.layer.0.SelfAttention.v.lora_A', 'encoder.block.9.layer.0.SelfAttention.v.lora_B']
- This IS expected if you are initializing T5ForConditionalGeneration from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing T5ForConditionalGeneration from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
Generating C# to Java translation ...
['public void serialize(LittleEndianOutput out) {out.writeShort(field_1_vcenter);}', 'public void addAll(BlockList<T> src) {if (src.size == 0)return;int srcDirIdx = 0;for (; srcDirIdx < src.tailDirIdx; srcDirIdx++)addAll(src.directory[srcDirIdx], 0, BLOCK_SIZE);if (src.tailBlkIdx != 0)addAll(src.tailBlock, 0, src.tailBlkIdx);}', 'public void writeByte(byte b) {if (upto == blockSize) {if (currentBlock != null) {addBlock(currentBlock);}currentBlock = new byte[blockSize];upto = 0;}currentBlock[upto++] = b;}', 'public ObjectId getObjectId() {return objectId;}', 'public DeleteDomainEntryResult deleteDomainEntry(DeleteDomainEntryRequest request) {request = beforeClientExecution(request);return executeDeleteDomainEntry(request);}', 'public long ramBytesUsed() {return ((termOffsets!=null)? termOffsets.ramBytesUsed() : 0) +((termsDictOffsets!=null)? termsDictOffsets.ramBytesUsed() : 0);}', 'public final String getFullMessage() {byte[] raw = buffer;int msgB = RawParseUtils.tagMessage(raw, 0);if (msgB < 0) {return ""; }return RawParseUtils.decode(guessEncoding(), raw, msgB, raw.length);}', 'public POIFSFileSystem() {this(true);_header.setBATCount(1);_header.setBATArray(new int[]{1});BATBlock bb = BATBlock.createEmptyBATBlock(bigBlockSize, false);bb.setOurBlockIndex(1);_bat_blocks.add(bb);setNextBlock(0, POIFSConstants.END_OF_CHAIN);setNextBlock(1, POIFSConstants.FAT_SECTOR_BLOCK);_property_table.setStartBlock(0);}', 'public void init(int address) {slice = pool.buffers[address >> ByteBlockPool.BYTE_BLOCK_SHIFT];assert slice != null;upto = address & ByteBlockPool.BYTE_BLOCK_MASK;offset0 = address;assert upto < slice.length;}', 'public SubmoduleAddCommand setPath(String path) {this.path = path;return this;}', 'public ListIngestionsResult listIngestions(ListIngestionsRequest request) {request = beforeClientExecution(request);return executeListIngestions(request);}', 'public QueryParserTokenManager(CharStream stream, int lexState){this(stream);SwitchTo(lexState);}', 'public GetShardIteratorResult getShardIterator(GetShardIteratorRequest request) {request = beforeClientExecution(request);return executeGetShardIterator(request);}', 'public ModifyStrategyRequest() {super("aegis", "2016-11-11", "ModifyStrategy", "vipaegis");setMethod(MethodType.POST);}', 'public boolean ready() throws IOException {synchronized (lock) {if (in == null) {throw new IOException("InputStreamReader is closed");}try {return bytes.hasRemaining() || in.available() > 0;} catch (IOException e) {return false;}}}', 'public EscherOptRecord getOptRecord() {return _optRecord;}', 'public synchronized int read(byte[] buffer, int offset, int length) {if (buffer == null) {throw new NullPointerException("buffer == null");}Arrays.checkOffsetAndCount(buffer.length, offset, length);if (length == 0) {return 0;}int copylen = count - pos < length ? count - pos : length;for (int i = 0; i < copylen; i++) {buffer[offset + i] = (byte) this.buffer.charAt(pos + i);}pos += copylen;return copylen;}', 'public OpenNLPSentenceBreakIterator(NLPSentenceDetectorOp sentenceOp) {this.sentenceOp = sentenceOp;}', 'public void print(String str) {write(str != null ? str : String.valueOf((Object) null));}', 'public NotImplementedFunctionException(String functionName, NotImplementedException cause) {super(functionName, cause);this.functionName = functionName;}'] ['public void serialize(LittleEndianOutput out) {out.writeShort(field_1_vcenter);}\n', 'public void addAll(BlockList<T> src) {if (src.size == 0) {return;}intsrcDirIdx = 0;for (;srcDirIdx < src.tailDirIdx % ;srcDirIdx++) {addAll(src.directory[srcDirIdx],0, BLOCK_SIZE);if (src.tailBlkIdx != 0) {addAll(src.tailBlock,0,src.tailBlkIdx);}addAll(src.tailBlock,0,src.tailBlkIdx);}addAll(src.tailBlock,0,src.tailBlkIdx);}\n', 'public void writeByte(byteb) {if (upto == null) {blockSize = blockSize;if (currentBlock != null) {addBlock(currentBlock);blockEnd.add(upto);}}currentBlock = newbyte[blockSize];upto = 0;}currentBlock[upto++] = b;}\n', 'public ObjectId getObjectId() {return objectId;}\n', 'public DeleteDomainEntryResult deleteDomainEntry(DeleteDomainEntryRequest request) {request = beforeClientExecution(request);return executeDeleteDomainEntry(request);}\n', 'public int ramBytesUsed() {return fst == null ? 0 : fst.ramBytesUsed();}\n', 'public final String getFullMessage() {byte[] raw = buffer;int msgB = RawParseUtils.tagMessage(raw, 0);if (msgB < 0) {return ""; }int msgB = RawParseUtils.tagMessage(raw, 0);if (msgB < 0) {return "";}}int msgB = RawParseUtils.tagMessage(raw, 0);if (msgB < 0) {return ""; }int msgB = RawParseUtils.tagMessage(raw, 0);if (msgB < 0) {return "";}}if (raw == null) {returnRawParseUtils.decode(guessEncoding(), raw, msgB, raw.length);}return RawParseUtils.decode(guessEncoding(), raw, msgB, raw.length);}\n', 'public POIFSFileSystem() {this(newHeaderBlock(bigBlockSize));_property_table = newPropertyTable(headerBlock);_documents = newArrayList();_root = null;}\n', 'public void init(int address) {slice = pool.buffers[address >> ByteBlockPool.BYTE_BLOCK_SHIFT];assert slice != null;upto = address & ByteBlockPool.BYTE_BLOCK_MASK;offset = address;assert upto < slice.length;}\n', 'public SubmoduleAddCommand setPath(String path) {this.path = path;return this;}\n', 'public ListIngestionsResult listIngestions(ListIngestionsRequest request) {request = beforeClientExecution(request);return executeListIngestions(request);}\n', 'public QueryParserTokenManager(CharStream stream,int lexState){this(stream);SwitchTo(lexState);}\n', 'public GetShardIteratorResult getSkillIterator(GetShardIteratorRequest request) {request = beforeClientExecution(request);return executeGetShardIterator(request);}\n', 'public ModifyStrategyRequest() {super("aegis","2016-11-11","ModifyStrategy","vipaegis");setMethod(MethodType.POST);}\n', 'public boolean ready() throws IOException {synchronized (lock) {if (in == null) {throw new IOException("InputStreamReader is closed");}}try {returnbytes.hasRemaining() || in.available() > 0;} catch (IOException e) {return false;}return bytes.available() || in.available() > 0;} catch (IOException e) {return false;}\n', 'public EscherOptRecord getOptRecord() {return _optRecord;}\n', 'public synchronized int read(byte[] buffer,int offset,int length) throws IOException {if (buffer == null) {throw newNullException(nameof(buffer));}Arrays.checkOffsetAndCount(buffer.length, offset, length);0) if (length == 0) {return 0;}int available = count-pos;intcopylen = available<length ? available:length;for (inti=0;i<copylen;i++) {buffer[offset+i] = (byte) this.buffer[pos+i]);}pos += copylen;return copylen;}}\n', 'public OpenNLPSentenceBreakIterator(NLPSentenceDetectorOpsentence0p) {this.sentenceOp = sentence0p;}\n', 'public void print(String str) {write(str ? String.valueOf(str));}\n', 'public NotImplementedFunctionException(StringfunctionName,ThrowableCause) {super(functionName,cause);this.functionName = functionName;}\n']
Exact Match: 30.00%

Downloading builder script:   0%|          | 0.00/5.94k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/3.34k [00:00<?, ?B/s]

BLEU: 0.6817382238665896

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained("codet5_lora_final")
tokenizer = AutoTokenizer.from_pretrained("codet5_lora_final")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

#javaToCSharp(tokenizer, model, device)
#cSharpToJava(tokenizer, model, device)

#java code from ocr
java_code = run_specific('java',clean=True)
print(java_code)
translation = javaToCSharp_specificTranslation(tokenizer,model,device,java_code)
print(translation)

Some weights of the model checkpoint at codet5_lora_final were not used when initializing T5ForConditionalGeneration: ['decoder.block.0.layer.0.SelfAttention.q.lora_A', 'decoder.block.0.layer.0.SelfAttention.q.lora_B', 'decoder.block.0.layer.0.SelfAttention.v.lora_A', 'decoder.block.0.layer.0.SelfAttention.v.lora_B', 'decoder.block.0.layer.1.EncDecAttention.q.lora_A', 'decoder.block.0.layer.1.EncDecAttention.q.lora_B', 'decoder.block.0.layer.1.EncDecAttention.v.lora_A', 'decoder.block.0.layer.1.EncDecAttention.v.lora_B', 'decoder.block.1.layer.0.SelfAttention.q.lora_A', 'decoder.block.1.layer.0.SelfAttention.q.lora_B', 'decoder.block.1.layer.0.SelfAttention.v.lora_A', 'decoder.block.1.layer.0.SelfAttention.v.lora_B', 'decoder.block.1.layer.1.EncDecAttention.q.lora_A', 'decoder.block.1.layer.1.EncDecAttention.q.lora_B', 'decoder.block.1.layer.1.EncDecAttention.v.lora_A', 'decoder.block.1.layer.1.EncDecAttention.v.lora_B', 'decoder.block.10.layer.0.SelfAttention.q.lora_A', 'decoder.block.10.layer.0.SelfAttention.q.lora_B', 'decoder.block.10.layer.0.SelfAttention.v.lora_A', 'decoder.block.10.layer.0.SelfAttention.v.lora_B', 'decoder.block.10.layer.1.EncDecAttention.q.lora_A', 'decoder.block.10.layer.1.EncDecAttention.q.lora_B', 'decoder.block.10.layer.1.EncDecAttention.v.lora_A', 'decoder.block.10.layer.1.EncDecAttention.v.lora_B', 'decoder.block.11.layer.0.SelfAttention.q.lora_A', 'decoder.block.11.layer.0.SelfAttention.q.lora_B', 'decoder.block.11.layer.0.SelfAttention.v.lora_A', 'decoder.block.11.layer.0.SelfAttention.v.lora_B', 'decoder.block.11.layer.1.EncDecAttention.q.lora_A', 'decoder.block.11.layer.1.EncDecAttention.q.lora_B', 'decoder.block.11.layer.1.EncDecAttention.v.lora_A', 'decoder.block.11.layer.1.EncDecAttention.v.lora_B', 'decoder.block.2.layer.0.SelfAttention.q.lora_A', 'decoder.block.2.layer.0.SelfAttention.q.lora_B', 'decoder.block.2.layer.0.SelfAttention.v.lora_A', 'decoder.block.2.layer.0.SelfAttention.v.lora_B', 'decoder.block.2.layer.1.EncDecAttention.q.lora_A', 'decoder.block.2.layer.1.EncDecAttention.q.lora_B', 'decoder.block.2.layer.1.EncDecAttention.v.lora_A', 'decoder.block.2.layer.1.EncDecAttention.v.lora_B', 'decoder.block.3.layer.0.SelfAttention.q.lora_A', 'decoder.block.3.layer.0.SelfAttention.q.lora_B', 'decoder.block.3.layer.0.SelfAttention.v.lora_A', 'decoder.block.3.layer.0.SelfAttention.v.lora_B', 'decoder.block.3.layer.1.EncDecAttention.q.lora_A', 'decoder.block.3.layer.1.EncDecAttention.q.lora_B', 'decoder.block.3.layer.1.EncDecAttention.v.lora_A', 'decoder.block.3.layer.1.EncDecAttention.v.lora_B', 'decoder.block.4.layer.0.SelfAttention.q.lora_A', 'decoder.block.4.layer.0.SelfAttention.q.lora_B', 'decoder.block.4.layer.0.SelfAttention.v.lora_A', 'decoder.block.4.layer.0.SelfAttention.v.lora_B', 'decoder.block.4.layer.1.EncDecAttention.q.lora_A', 'decoder.block.4.layer.1.EncDecAttention.q.lora_B', 'decoder.block.4.layer.1.EncDecAttention.v.lora_A', 'decoder.block.4.layer.1.EncDecAttention.v.lora_B', 'decoder.block.5.layer.0.SelfAttention.q.lora_A', 'decoder.block.5.layer.0.SelfAttention.q.lora_B', 'decoder.block.5.layer.0.SelfAttention.v.lora_A', 'decoder.block.5.layer.0.SelfAttention.v.lora_B', 'decoder.block.5.layer.1.EncDecAttention.q.lora_A', 'decoder.block.5.layer.1.EncDecAttention.q.lora_B', 'decoder.block.5.layer.1.EncDecAttention.v.lora_A', 'decoder.block.5.layer.1.EncDecAttention.v.lora_B', 'decoder.block.6.layer.0.SelfAttention.q.lora_A', 'decoder.block.6.layer.0.SelfAttention.q.lora_B', 'decoder.block.6.layer.0.SelfAttention.v.lora_A', 'decoder.block.6.layer.0.SelfAttention.v.lora_B', 'decoder.block.6.layer.1.EncDecAttention.q.lora_A', 'decoder.block.6.layer.1.EncDecAttention.q.lora_B', 'decoder.block.6.layer.1.EncDecAttention.v.lora_A', 'decoder.block.6.layer.1.EncDecAttention.v.lora_B', 'decoder.block.7.layer.0.SelfAttention.q.lora_A', 'decoder.block.7.layer.0.SelfAttention.q.lora_B', 'decoder.block.7.layer.0.SelfAttention.v.lora_A', 'decoder.block.7.layer.0.SelfAttention.v.lora_B', 'decoder.block.7.layer.1.EncDecAttention.q.lora_A', 'decoder.block.7.layer.1.EncDecAttention.q.lora_B', 'decoder.block.7.layer.1.EncDecAttention.v.lora_A', 'decoder.block.7.layer.1.EncDecAttention.v.lora_B', 'decoder.block.8.layer.0.SelfAttention.q.lora_A', 'decoder.block.8.layer.0.SelfAttention.q.lora_B', 'decoder.block.8.layer.0.SelfAttention.v.lora_A', 'decoder.block.8.layer.0.SelfAttention.v.lora_B', 'decoder.block.8.layer.1.EncDecAttention.q.lora_A', 'decoder.block.8.layer.1.EncDecAttention.q.lora_B', 'decoder.block.8.layer.1.EncDecAttention.v.lora_A', 'decoder.block.8.layer.1.EncDecAttention.v.lora_B', 'decoder.block.9.layer.0.SelfAttention.q.lora_A', 'decoder.block.9.layer.0.SelfAttention.q.lora_B', 'decoder.block.9.layer.0.SelfAttention.v.lora_A', 'decoder.block.9.layer.0.SelfAttention.v.lora_B', 'decoder.block.9.layer.1.EncDecAttention.q.lora_A', 'decoder.block.9.layer.1.EncDecAttention.q.lora_B', 'decoder.block.9.layer.1.EncDecAttention.v.lora_A', 'decoder.block.9.layer.1.EncDecAttention.v.lora_B', 'encoder.block.0.layer.0.SelfAttention.q.lora_A', 'encoder.block.0.layer.0.SelfAttention.q.lora_B', 'encoder.block.0.layer.0.SelfAttention.v.lora_A', 'encoder.block.0.layer.0.SelfAttention.v.lora_B', 'encoder.block.1.layer.0.SelfAttention.q.lora_A', 'encoder.block.1.layer.0.SelfAttention.q.lora_B', 'encoder.block.1.layer.0.SelfAttention.v.lora_A', 'encoder.block.1.layer.0.SelfAttention.v.lora_B', 'encoder.block.10.layer.0.SelfAttention.q.lora_A', 'encoder.block.10.layer.0.SelfAttention.q.lora_B', 'encoder.block.10.layer.0.SelfAttention.v.lora_A', 'encoder.block.10.layer.0.SelfAttention.v.lora_B', 'encoder.block.11.layer.0.SelfAttention.q.lora_A', 'encoder.block.11.layer.0.SelfAttention.q.lora_B', 'encoder.block.11.layer.0.SelfAttention.v.lora_A', 'encoder.block.11.layer.0.SelfAttention.v.lora_B', 'encoder.block.2.layer.0.SelfAttention.q.lora_A', 'encoder.block.2.layer.0.SelfAttention.q.lora_B', 'encoder.block.2.layer.0.SelfAttention.v.lora_A', 'encoder.block.2.layer.0.SelfAttention.v.lora_B', 'encoder.block.3.layer.0.SelfAttention.q.lora_A', 'encoder.block.3.layer.0.SelfAttention.q.lora_B', 'encoder.block.3.layer.0.SelfAttention.v.lora_A', 'encoder.block.3.layer.0.SelfAttention.v.lora_B', 'encoder.block.4.layer.0.SelfAttention.q.lora_A', 'encoder.block.4.layer.0.SelfAttention.q.lora_B', 'encoder.block.4.layer.0.SelfAttention.v.lora_A', 'encoder.block.4.layer.0.SelfAttention.v.lora_B', 'encoder.block.5.layer.0.SelfAttention.q.lora_A', 'encoder.block.5.layer.0.SelfAttention.q.lora_B', 'encoder.block.5.layer.0.SelfAttention.v.lora_A', 'encoder.block.5.layer.0.SelfAttention.v.lora_B', 'encoder.block.6.layer.0.SelfAttention.q.lora_A', 'encoder.block.6.layer.0.SelfAttention.q.lora_B', 'encoder.block.6.layer.0.SelfAttention.v.lora_A', 'encoder.block.6.layer.0.SelfAttention.v.lora_B', 'encoder.block.7.layer.0.SelfAttention.q.lora_A', 'encoder.block.7.layer.0.SelfAttention.q.lora_B', 'encoder.block.7.layer.0.SelfAttention.v.lora_A', 'encoder.block.7.layer.0.SelfAttention.v.lora_B', 'encoder.block.8.layer.0.SelfAttention.q.lora_A', 'encoder.block.8.layer.0.SelfAttention.q.lora_B', 'encoder.block.8.layer.0.SelfAttention.v.lora_A', 'encoder.block.8.layer.0.SelfAttention.v.lora_B', 'encoder.block.9.layer.0.SelfAttention.q.lora_A', 'encoder.block.9.layer.0.SelfAttention.q.lora_B', 'encoder.block.9.layer.0.SelfAttention.v.lora_A', 'encoder.block.9.layer.0.SelfAttention.v.lora_B']
- This IS expected if you are initializing T5ForConditionalGeneration from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing T5ForConditionalGeneration from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

publicintjump(int()nums){intn=nums.length;int[]dp=newint[n];for(inti=1;i<n;i++){intsteps=Integer.MAX_VALUE;for(intj=i−1;j>=0;j--){if(dp[j]!=Integer.MAX_VALUE&&nums[j]+j>=i){steps=Math.min(steps,dp[j]+1);}=dp[i]steps;}}}returndp[n-1];
Generating Java to C# translation ...
public int jump(int()nums) {final int n =nums.length;final int[] dp = new int[n];for (int i = 1; i < n; i++) {intsteps = Integer.MAX_VALUE;for (int j = i−1; j >=0; j--) {if (dp[j] != Integer.MAX_VALUE&&nums[j]+j>=i) {steps = Math.min(steps,dp[j]+1);} = dp[i]steps;}}}return dp[n-1];}